### ISSUE TITLE
How to version the ServiceWorker?

### ISSUE THREAD

**Issue by mrmartineau** [hanford/next-offline#10]
@hanford do you know how to version the generated service worker? Or, rather, how does this plugin change the service worker (SW) file so that a new version is requested by a user's browser?

It looks like the SW changes on each build from next, so does that mean it wouldn't change until a new deployment/build of next?

**Comment by hanford** [comment]
that is correct @mrmartineau , currently `next-offline` is piggybacking heavily on the newest version of [workbox](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) which basically just creates a new version every deploy. 

I think you can fine tune that, but you'd have to follow the documentation ^

**Comment by mrmartineau** [comment]
@hanford thanks for the clarification, and for creating this plugin. Was setting it up on my site yesterday.
