### ISSUE TITLE
Precache-manifest, how to generate and route ?

### ISSUE THREAD

**Issue by revskill10** [hanford/next-offline#102]
When i build with `next build`, i could see `precache-manifest....js` generated at `.next/` folder.
But when built on Now 2, i don't see it got generated anywhere.

Secondly, current Now 2 example doesn't have any route to `precache-manifest...js`, i don't know how to route to that file, one reason is because i don't see it got generated on Now 2.

**Comment by hanford** [comment]
@revskill10 ingnore that generated file, the one you should be paying attention to is `service-worker.js` (we use precache manifest from a different plugin, and then generate what we need into the service worker)

For how to get stuff set up on Now 2.0, I'd look at the [documentation](https://github.com/hanford/next-offline#now-20) and the [example now 2.0 app](https://github.com/hanford/next-offline/tree/master/examples/now2).

Going to close this issue as it isn't totally relevant to the project - feel free to open another if you find something specific!
