### ISSUE TITLE
Serving sitemap.xml and robots.txt files

### ISSUE THREAD

**Issue by ValentinGurkov** [hanford/next-offline#104]
Hello everyone,

I'm trying to learn how to serve my app offline and this plugin is really helpful, though I'm having trouble configuring the service worker to also serve my sitemap. Currently in tries to get the sitemap from `/pages/sitemap.xml.js` and robots `/pages/robots.txt.js` but it is available in `/sitemap.xml` and `/robots.txt` like in any other site.

My server generates a sitemap on a to to `/sitemap.xml` and `/robots.txt`

```javascript
 server.get('/robots.txt', (req, res) => res.status(200).sendFile('robots.txt', robotsOptions))

 server.get('/sitemap.xml', async (req, res) => {
      const sitemap = await generateSitemap()
      sitemap.toXML((err, xml) => {
        if (err) {
          res.status(500).end()
          return
        }

        res.header('Content-Type', 'application/xml;charset=UTF-8')
        res.status(200).send(xml)
      })
    })
```
And here's my `workboxOpts` configuration:
```javascript
workboxOpts: {
      swDest: 'static/service-worker.js',
      clientsClaim: true,
      skipWaiting: true,
      globPatterns: ['.next/static/*', '.next/static/commons/*'],
      modifyUrlPrefix: {
        '.next': '/_next'
      },
      runtimeCaching: [
        {
          urlPattern: '/',
          handler: 'networkFirst',
          options: {
            cacheName: 'html-cache'
          }
        },
        {
          urlPattern: /\/blog\//,
          handler: 'networkFirst',
          options: {
            cacheName: 'html-cache'
          }
        },
        {
          urlPattern: /\/sitemap\.xml$/,
          handler: 'networkFirst',
          options: {
            cacheName: 'html-cache'
          }
        },
        {
          urlPattern: /.*\.(?:png|jpg|jpeg|svg|gif)/,
          handler: 'cacheFirst',
          options: {
            cacheName: 'image-cache',
            cacheableResponse: {
              statuses: [0, 200]
            }
          }
        }
      ]
    },
```

It's probably something I've missed completely and I would be thankful if somebody could point me in the right direction.

Thanks,
Valentin

**Comment by hanford** [comment]
@ValentinGurkov This is a good idea! I'm currently on holiday and can take a deeper look afterwards. Should be back ~first weekend in January.

PR's are welcome if you can get something working by modifying `next-offline`!

**Comment by hanford** [comment]
Hey friends .. going to close this due to inactivity. If this is still a desired feature, open a new issue and maybe we can dig deeper!
