### ISSUE TITLE
Give error in IE11

### ISSUE THREAD

**Issue by nisargrthakkar** [hanford/next-offline#113]
Hi Team

I had integrated next-offline for PWA before integrated next-offline my site perfectly working fine with IE11 with polyfills and next-offline give me following error while working with IE11. 

![next-offline](https://user-images.githubusercontent.com/26029722/50952882-c65cb780-14d7-11e9-95fe-439e8d707f89.png)
![next-offline1](https://user-images.githubusercontent.com/26029722/50952884-c65cb780-14d7-11e9-94e1-d49a8dc8df3d.png)

**Comment by hanford** [comment]
@nisargrthakkar any idea what specific line is throwing the error? Could it be the arrow function? 

I'd be happy to have compatibility if it's not too hard

**Comment by nisargrthakkar** [comment]
Yes, it is arrow function I guess. I shared a screenshot of the error 

 `navigator.serviceWorker.ready.then(registration => {`  Gives error.

![next-offline 2](https://user-images.githubusercontent.com/26029722/51016491-8c061f80-1596-11e9-8cb2-1d07e109e0f1.png)

**Comment by hanford** [comment]
I've removed the arrow function in favor of the `function` keyword and next-offline version `3.3.3` includes the fix.

Feel free to open another issue if you run into something else!

**Comment by nisargrthakkar** [comment]
Thank you @hanford for your update. 

I updated next-offline to 3.3.3 to version that fixed issue that I have previously shared but Now I got the following issue in register function 

Console :
![next-offline 3](https://user-images.githubusercontent.com/26029722/51231678-51332b80-198a-11e9-8d9b-e9897e37ad2f.png)

File Line :
![next-offline 4](https://user-images.githubusercontent.com/26029722/51231683-51332b80-198a-11e9-84d2-a36d5beda5c3.png)

**Comment by hanford** [comment]
@nisargrthakkar ahh, looks like it doesn't like the default argument, I'll post a fix with an ES5 alternative.

**Comment by hanford** [comment]
Can you try version `3.3.4`? just released it with the fix

**Comment by nisargrthakkar** [comment]
Hi @hanford 

Thank you for your quick response 

I tried with 3.3.4 version but I got following error

![next-offline 5](https://user-images.githubusercontent.com/26029722/51389807-7f179c00-1b53-11e9-8964-4259666257cf.png)
![next-offline 6](https://user-images.githubusercontent.com/26029722/51389808-7f179c00-1b53-11e9-811d-4e7e0eba2566.png)

**Comment by hanford** [comment]
@nisargrthakkar that should be fixed by this commit: https://github.com/hanford/next-offline/commit/fb7e385aa43352c4d9bf787d259b4d17c62cb922

released another patch, `v3.3.5`

**Comment by nisargrthakkar** [comment]
Hi @hanford 

It is working perfectly. Thank you for your quick updates.
