### ISSUE TITLE
failing dev tools audits progressive wep app

### ISSUE THREAD

**Issue by himadrinath** [hanford/next-offline#118]
@hanford  i don't understand what am i missing in this if i test it in my local env its successful but when i deployed it and test it its getting failed.
service worker registering cache working. but when i test it i am getting this result.

<img width="1080" alt="screenshot 2019-02-04 at 12 21 20 pm" src="https://user-images.githubusercontent.com/12247490/52194190-d7031200-2878-11e9-81ea-c9b21c4ee236.png">

when i tried to install it in my mobile device its working just fine.

here is my service-worker
`self.__precacheManifest = [
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/notifications.js"
  },
  {
    "url": "/_next/static/css/commons.6673736f.chunk.css"
  },
  {
    "url": "/_next/static/css/styles.c151c423.chunk.css"
  },
  {
    "url": "/_next/static/runtime/main-00b1dce2c60bc0b3cbea.js"
  },
  {
    "url": "/_next/static/runtime/webpack-a4aebfad53c3034be927.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/_error.js"
  },
  {
    "url": "/_next/static/chunks/styles.63a82fae5a20906ab0ae.js"
  },
  {
    "url": "/_next/static/chunks/15.6a5a659f89cdd0fdb203.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/about.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/compose/page.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/create/profile.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/index.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/messages.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/network/offline.js"
  },
  {
    "url": "/_next/static/chunks/commons.ece56a39edc10bedb35b.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/profile.js"
  },
  {
    "url": "/_next/static/chunks/23.f60ac2dc1b63c14a1ed3.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/auth/success.js"
  },
  {
    "url": "/_next/static/chunks/16.9d131141f90a35898b31.js"
  },
  {
    "url": "/_next/static/chunks/17.ca2df297dfdd0eef14db.js"
  },
  {
    "url": "/_next/static/chunks/18.152a517f039d3cfb9de2.js"
  },
  {
    "url": "/_next/static/chunks/19.6a2d5ea02d12738be8f2.js"
  },
  {
    "url": "/_next/static/chunks/20.b73fa55b8166b27d6586.js"
  },
  {
    "url": "/_next/static/chunks/21.9f6e9d81bf62054c7b8f.js"
  },
  {
    "url": "/_next/static/chunks/22.25fbb42445dc408ea8b0.js"
  },
  {
    "url": "/_next/static/0W6WdsdNyaWJVLxQPOXxz/pages/_app.js"
  }
];

/**
 * Welcome to your Workbox-powered service worker!
 *
 * You'll need to register this file in your web app and you should
 * disable HTTP caching for this file too.
 * See https://goo.gl/nhQhGp
 *
 * The rest of the code is auto-generated. Please don't update this file
 * directly; instead, make changes to your Workbox build configuration
 * and re-run your build process.
 * See https://goo.gl/2aRDsh
 */

importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js");

importScripts(
  
);

workbox.core.setCacheNameDetails({prefix: "inpage"});

/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.routing.registerNavigationRoute("network/offline", {
  whitelist: [/^\/page/],
  blacklist: [/^[a-zA-Z]+$/],
});

workbox.routing.registerRoute(/\.(?:js|css)$/, workbox.strategies.staleWhileRevalidate(), 'GET');
workbox.routing.registerRoute(/\.(?:png|gif|jpg|jpeg)$/, workbox.strategies.cacheFirst({ "cacheName":"images", plugins: [new workbox.expiration.Plugin({"maxEntries":150,"maxAgeSeconds":2592000,"purgeOnQuotaError":false})] }), 'GET');
`

what am i missing?

**Comment by himadrinath** [comment]
@hanford here is the link [url](https://inpage.azurewebsites.net/HimadriNath)

i fixed some of this but their is another thing after page load if i refresh the page its go to the 'navigateFallback' url i don't understand why

here is my next.config.js

`const withOffline = require("next-offline");
const withCSS = require("@zeit/next-css");
// fix: prevents error when .css files are required by node
if (typeof require !== "undefined") {
  require.extensions[".css"] = file => {};
}
module.exports = withOffline(
  withCSS({
    useFileSystemPublicRoutes: false,
    workboxOpts: {
      cacheId: "inpage",
      clientsClaim: false,
      skipWaiting: false,
      navigateFallback: "/index.html",
      navigateFallbackWhitelist: [/page/, /^\/[a-zA-Z]+$/],
      runtimeCaching: [
        {
          //https://googlechromelabs.github.io/sw-toolbox/api.html#handlers
          handler: "staleWhileRevalidate",
          urlPattern: /\.(?:js|css)$/
        },
        {
          handler: "cacheFirst",
          urlPattern: /\.(?:png|gif|jpg|jpeg)$/,
          options: {
            cacheName: "images",
            expiration: {
              maxEntries: 150,
              maxAgeSeconds: 30 * 24 * 60 * 60 // 1 month
            }
          }
        }
      ]
    },
 webpack: (config, { defaultLoaders }) => {
      config.node = {
        fs: "empty"
      };
      return config;
    }
  })
);`

**Comment by hanford** [comment]
@himadrinath because you're not serving the website from the root, you need to specify a `scope` for your service worker. You can check out the next-offline options that are available here: https://github.com/hanford/next-offline#next-offline-options

But I'm going to go ahead and close this because it doesn't seem to be an issue with the library itself
