### ISSUE TITLE
service-worker.js:1 Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by theallseingeye** [hanford/next-offline#119]
I get a lot of these errors since activating next-offline on my app, is this normal? It normally only happens after a page refresh

```
service-worker.js:1 Uncaught (in promise) DOMException
```

I also get a lot of notices about this:

```
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I assume this is from using `<Link prefetch>` is this normal, or should I be tweaking how I handle this with next-offline

**Comment by theallseingeye** [comment]
My serviceworker cache is using about 600mb, is this normal?

**Comment by hanford** [comment]
@theallseingeye I think your `Link` warnings are unrelated to next-offline but not totally certain.

As for the cache, that is high .. but I don't think it's totally out of the ordinary. If you want, workbox gives you pretty fine grain control over what is/isn't cached and by default next-offline will cache as much as possible.

You can tweak this by passing in your own cache rules like [this](https://github.com/hanford/next-offline#cache-strategies). If you're not familiar with this, I'd recommend this blog post explaining the different strategies https://jakearchibald.com/2014/offline-cookbook/

Going to go ahead and close this issue, feel free to open more if you additional questions

**Comment by theallseingeye** [comment]
Do you have some suggestions on how to debug this? My app seems to load up fine, I get 15mb service cache. But it seems after a few days it suddenly hits 1.3GB

My .next folder is only 65mb, any other ideas? I tried looking into chrome dev tools but even when I clear all the caches it still says my sw cache is 1.3GB

**Comment by theallseingeye** [comment]
Also I get a lot of this:

```
service-worker.js:1 Uncaught (in promise) DOMException
```

I think this is related to the service-worker?

**Comment by hanford** [comment]
@theallseingeye it could be workbox just aggressively caching things, I've read on their documentation that they will often hit the upper limits for browser cacheing which is what is causing

```
service-worker.js:1 Uncaught (in promise) DOMException
```

Keep in mind workbox is caching all API calls that occur along with all assets, so if you're transmitting lots of data a lot of that will end up in the cache too.

We're currently using workbox 3.6.3, while the workbox team is actively working on the next version (4.0) it's currently still in beta.

It looks like 4.0 fixes this issue, (according to this: https://github.com/GoogleChrome/workbox/issues/1840) .. Though I likely won't increase the version for next-offline until 4.0 stable is released.

This reminds me, you can also trying adding some expiration rules to your cache strategy and expire things after a week or any timeframe you think is helpful for your users. I've seen ~1 week, but you could even do seconds. 

```js
const withOffline = require('next-offline')

module.exports = withOffline({
  workboxOpts: {
    runtimeCaching: [
      {
        urlPattern: /.png$/,
        handler: 'cacheFirst'

      },
      {
        urlPattern: /api/,
        handler: 'networkFirst',
        options: {
	      cacheExpiration: {
    	    maxEntries: 50,
        	maxAgeSeconds: 300 // 5 minutes
	      },
          cacheableResponse: {
            statuses: [0, 200],
            headers: {
              'x-test': 'true'
            }
          }
        }
      }
    ]
  }
})
```

I'm pretty certain that `maxAgeSeconds` with `maxEntries` will solve your issue so I'm going to go ahead and close once more. 

Feel free to open another issue or report back!
