### ISSUE TITLE
Internal server Error when refreshing the page when offline

### ISSUE THREAD

**Issue by ivanarielcaceres** [hanford/next-offline#120]
Hi there,
I've been having some difficulty getting the plugin to work well in a project.
I would greatly appreciate a support from you

**Expected Behavior**

When refreshing the page while offline it should work even if it has not been previously refreshed when connected to the internet.

**Current Behavior**
By navigating to a page that was not previously refreshed while online. When switching to offline mode and refreshing the page this results in internal server error because the server tries to fetch the API. On the client side, without refresh it works well.

**Steps to Reproduce**
**ONLINE**
- Navigate to PAGE 1
- Navigate to PAGE 2 (Fetch data on getInitialProps)
- Return to PAGE 1

**OFFLINE**
- Navigate to PAGE 2 (Fetch data on getInitialProps)
- Refresh the page

Example project base on next example; [Example](https://github.com/ivanarielcaceres/next-offline-example/tree/master/examples/now1)

**Comment by hanford** [comment]
Hopefully will have some time to take a look this weekend, been very busy at work lately!

**Comment by jeffVolt** [comment]
I have the same problem!!!

**Comment by astrosalinas** [comment]
I have the same problem!
please help

**Comment by Astrobboy** [comment]
same problem here

**Comment by hanford** [comment]
I'm working on upgrade `workbox` to v4.0.0, it's a library we're using under the hood to power `next-offline`

Anyways, I'm having some trouble reproducing this with the latest version of workbox and my personal website, so maybe it's fixed? 🤞

My website with the latest code for next-offline can be found [here](https://personal-website-ck7wzn736.now.sh/) it has a server side rendered route in which we use getInitialProps to fetch github repos.

Would one of you mind double checking to see if you can reproduce this bug in the environment above?

Alternatively you could try using `next-offline@4.0.0-beta.0`

Let me know, thanks!

**Comment by DouglasGabr** [comment]
@hanford I was able to reproduce the bug in your website:
1. Load the main page
2. Navigate to the Projects page
3. Go offline (I did in the Network tab, in devtools)
4. Refresh the page
5. Error!
If you look in the service worker cache, you see that it caches the javascript of the Projects page, but not the route itself, so the navigation works offline but the refresh don't.

**Comment by ivanarielcaceres** [comment]
@hanford , I was able to reproduce the bug too in your site.

When navigate to project page using Link from Next.js, the request (getInitialProps) is executed from client side and it's work perfectly. But when reload the page using f5 request (getInitialProps) is executed on the server side. That's the main problem :(

When navigate to project and hit f5 before go offline, it's work pefectly!
