### ISSUE TITLE
[Question] Using with Full CDN on Now v2

### ISSUE THREAD

**Issue by williamli** [hanford/next-offline#122]
According to the Full CDN instructions at https://zeit.co/docs/v2/deployments/concepts/cdn-and-global-distribution/

I should, set cache-control for the next site using

`Cache-Control: s-maxage=31536000, maxage=0`

> As you can see above, the header is now instructing the client to expire any caches for the resource immediately. In general, we recommend this because it leverages Now's caches across the Full CDN instead of depending on the client's as well.

Does it mean if I chose to use Full CDN, I should not use next-offline; and if I am using next-offline to cache the site with service worker on browsers, I should not use the Full CDN configurations?

**Comment by hanford** [comment]
I don't think so! I use the "Full CDN" on my personal website and also use next-offline.

Disregard browser caching, next-offline will only come into play if there is 0 network availability

You can see my personal website [here](https://github.com/hanford/personal-website)

**Comment by hanford** [comment]
Going to close this because it's not an issue with next-offline specifically
