### ISSUE TITLE
Getting error when compilation in dev mode

### ISSUE THREAD

**Issue by ibraelillo** [hanford/next-offline#123]
Hello, 

I'd like to report this bug I'm facing right now:

When compiling in dev mode with next 8.0.2, I'm receiving this error:

Module Not Found : Can't resolve './register-sw-compiled.js' 

Steps to reproduce: 
--------------------
Use this configuration
```
const withOffline = require('next-offline')
const SWPrecacheWebpackPlugin = require('sw-precache-webpack-plugin')

module.exports = withOffline({
  publicRuntimeConfig: {
    // activate locales on urls
    localeSubpaths: true,
    defaultLocaleSubpath: true,

    // languages
    languages: [
      'en', 'es', 'fr'
    ],
  },
  webpack: config => {

    // Fixes npm packages that depend on `fs` module
    config.node = {
      fs: 'empty'
    }

    config.plugins.push(
      new SWPrecacheWebpackPlugin({
        verbose: true,
        staticFileGlobsIgnorePatterns: [/\.next\//],
        runtimeCaching: [
          {
            handler: 'networkFirst',
            urlPattern: /^https?.*/
          }
        ]
      })
    )

    return config
  }
})
```
Expected result:
next compiles successfully and offline navigation works with service-worker noop

Actual result:
![screenshot 2019-03-04 at 11 58 21](https://user-images.githubusercontent.com/3011753/53729199-da3bee80-3e74-11e9-9dc0-01ca890ccce8.png)

The error is getting thrown from this code: 

<img width="859" alt="screenshot 2019-03-04 at 12 01 43" src="https://user-images.githubusercontent.com/3011753/53729343-4f0f2880-3e75-11e9-92b7-3f3eed4605fc.png">

Thank you all and hope this gets quickly resolved. If I can help ....

**Comment by hanford** [comment]
Currently on vacation @ibraelillo, will take a look afterwards

**Comment by hanford** [comment]
@ibraelillo can you easily reproduce this error in a repository where I can look?

At first glance you're using `SwPrecachePlugin` and next-offline, generally speaking next-offline should do everything that `SwPrecache` is doing so curious if you still need that.

**Comment by hanford** [comment]
Going to close due to inactivity .. if you run into this please open a new issue!
