### ISSUE TITLE
No manifest file

### ISSUE THREAD

**Issue by jan0991** [hanford/next-offline#125]
Running lighthouse I get the following:
```
User will not be prompted to Install the Web App
Failures: No manifest was fetched, Service worker does not successfully serve the manifest's start_url, No usable web app manifest found on page.
```
My config(but it gave same error just with nextoffline,  copied from docs): 

```
const withCSS = require('@zeit/next-css')
const { PHASE_DEVELOPMENT_SERVER } = require('next/constants')
const nextOffline = require('next-offline')
const path = require('path')
const withPlugins = require('next-compose-plugins')

module.exports = withPlugins(
    [
        [nextOffline, ['!', PHASE_DEVELOPMENT_SERVER]], [withCSS]
    ],
    {
        webpack: config => {
            config.resolve.modules = [
                path.resolve('./src'),
                path.resolve('./public'),
                'node_modules'
            ]
            return config
        },
        // Other Next.js config here...
    }
)
```

APP is served from root of the domain. next-offline is supposed to generate `manifest.json` right? Any ideas?

**Comment by CDharmateja** [comment]
I am not sure if next-offline will generate a `manifest.json` file but you can include it by creating it in `static` folder and linking it to the `Head` by importing `Head` from `next/head`.

**Comment by hanford** [comment]
@jan0991 next-offline doesn't generate a manifest.json, it generates a service worker.

Can you try removing next-compose-plugins and see if the issue continues?

**Comment by hanford** [comment]
Going to assume removing next-compose-plugins fixed the issue, we have a separate issue for that being tracked over here: https://github.com/hanford/next-offline/issues/69
