### ISSUE TITLE
staleWhileRevalidate bug

### ISSUE THREAD

**Issue by Emiliano-Bucci** [hanford/next-offline#133]
Hi to all! 

I think i found a weird bug when using the `staleWhileRevalidate` cache strategy. Currently i'm working on a headless wordpress site (Next.js + Apollo + graphQL) and decided to add the `next-offline` lib. so:

- When i first load the page, the `sw` is installed. (data is being fetched from the network).

- Second reload: data is still being fetched from the but the cache is being filled with the api response. 

- Third reload: data is loaded from the cache correctly.

Till here, everything seems ok; the issue appears the moment i create new content. 

Let's say i've created 10 posts. In the page i'll show 10 posts and this 10 posts are being cached by the `sw`. Then i create a new posts. The moment i reload the page happens that:
- The `sw` cache is being updated correctly with the fresh data.
- The front-end, though, still shows only 10 posts.
- Looking into the browser `view-source` i find that the new post is there! 

So the server did respond correctly and, somehow, the html served by the server display the correct and fresh data, though, for some reason, the front-end still render the old data. 

Any possible clues on this?? 
Thanks!

**Comment by lglossman** [comment]
That's how staleWhileRevalidated is intended to work, it returns the cached data (without the new post) while in the background it refreshes the cache but you won't see it take effect until the next reload.
