### ISSUE TITLE
Fails lighthouse audit when express compression is used

### ISSUE THREAD

**Issue by GusRuss89** [hanford/next-offline#136]
My setup is given in #134 

I got it working by adding `{ urlPattern: /^https?.*/, handler: 'networkFirst' }` as one of the commenters suggested.

However, it stops working - and fails the same audit - if I add Gzip compression. I.e. this:

```
app.use(compression())
```

I've tried filtering out the service worker so that it is not compressed:

```
function shouldCompress(req, res) {
  // don't compress the service worker
  if (req.path === '/service-worker.js') {
    return false
  }

  // fallback to standard filter function
  return compression.filter(req, res)
}
app.use(compression({ filter: shouldCompress }))
```

It has no effect.

Without compression I get poor performance scores in Lighthouse. With compression I get better performance scores, but I fail the PWA audit.

**Comment by hanford** [comment]
@GusRuss89 are you hosting on your own? I think `Now` does this stuff for you for free. (adds brotli compression!) 

I'm not that familiar with the compression middleware

**Comment by GusRuss89** [comment]
@hanford I think it was an issue introduced by one of my Chrome extensions. If I run the audit in an incognito tab it passes. I didn't realise my extensions influenced the report. Closing the issue.
