### ISSUE TITLE
Getting offline functionalties to work in DevMode

### ISSUE THREAD

**Issue by Erik-Sovereign** [hanford/next-offline#137]
Hello everyone, 
I was trying out the example in next-offline/examples/now2/. I "yarn install" 'd it and deployed it with now. Offline functionalities worked just great! 
It didn't work in dev mode though (yarn dev). The only change I made to the files, was adding "generateInDevMode" in  next.config.js
Like this:
`const nextConfig = {
  generateInDevMode: true,
  workboxOpts: {
...
`
The error thrown on localhost is:
`SW registration failed:  TypeError: "ServiceWorker script at http://localhost:3000/service-worker.js for scope http://localhost:3000/ encountered an error during installation."`

I have the same problem in the project I'm working on. The service worker is registered when hosted with now but not in dev mode. I hope we can fix the issue for everyone in the example so that I can fix it in my project afterwards.

My question is what addtional steps do I have to take to get this to work in dev mode? 
Another question is if the offline functionalities or more specific next-offline are generally expected to work in Dev Mode?

Thank you!

**Comment by hanford** [comment]
are you using `now dev` ?

We haven't _really_ spent much time making the plugin work in development other than ensuring the SW registers and stuff correctly.

**Comment by Erik-Sovereign** [comment]
Thanks for your time!
I tried it after you suggested it. Unfortutanely now dev isn't working for me. While looking at the issues of now-cli I think it is a Windows 10 issue. 

Do you know an alternative way than yarn dev or now dev to test Service Workers faster than with deploying the site with them every time?

**Comment by hanford** [comment]
@Erik-Sovereign `now dev` isn't actually working for me either over on my [personal website](https://github.com/hanford/personal-website). I'm about to take off on vacation for the next few days, but if I have some downtime I'll take a look

**Comment by Erik-Sovereign** [comment]
Thank you very much. I appreciate it.

**Comment by mrspeaker** [comment]
I am having the same issue - but it seems like it's in prod mode too? If I do a clean clone of the test example and build and `npm start`, it throws the same errors:

![Screenshot from 2019-05-14 17-14-04](https://user-images.githubusercontent.com/129330/57732829-f5448f00-766b-11e9-8ba7-ae04cfce720d.png)

(This is in Firefox, on Ubuntu)

**Comment by hanford** [comment]
@mrspeaker I'm not seeing those errors on my website in any browser (don't have access to Ubuntu) .. 

Can you share a screenshot of this happening on my website?

<img width="1460" alt="Screen Shot 2019-05-14 at 2 41 36 PM" src="https://user-images.githubusercontent.com/2148168/57734373-97597c80-7656-11e9-8a29-57f4251b5643.png">

**Comment by mrspeaker** [comment]
@hanford  - hmm, ok - it must be something in my Firefox then. I have my mac with me today and I'll see if I can figure out what it is. Here's what I get on your page (the warning is because I am blocking Segment.io, but I have white-listed everything else)

![Screenshot from 2019-05-14 17-58-57](https://user-images.githubusercontent.com/129330/57735319-317aee00-7672-11e9-96c9-f650058423de.png)

**Comment by hanford** [comment]
hey friends, going to close this in favor of https://github.com/hanford/next-offline/issues/155


I'd like to prioritize this and if I have some downtime this seems like the biggest issue people have.
