### ISSUE TITLE
Support Offline google analytics

### ISSUE THREAD

**Issue by Ktchan825** [hanford/next-offline#140]
Hi there, I just found that we could [enable google analytics with workbox](https://developers.google.com/web/tools/workbox/guides/enable-offline-analytics). I just wonder if there is any config supporting this features.

Any help would be appreciated, thank you!

**Comment by ScreamZ** [comment]
+1 @hanford

**Comment by Ktchan825** [comment]
@ScreamZ Hi, just add 
```
const workboxOpts = {
  offlineGoogleAnalytics: true
  ...
} 
withOffline(workboxOpts)
```
in your next.config.js

**Comment by ScreamZ** [comment]
All right thanks :)

**Comment by hanford** [comment]
Thanks @Ktchan825.

@ScreamZ I'm going to go ahead and close this issue. 

Feel free to open another if you run into anything else!

**Comment by graphicmist** [comment]
> @ScreamZ Hi, just add
> 
> ```
> const workboxOpts = {
>   offlineGoogleAnalytics: true
>   ...
> } 
> withOffline(workboxOpts)
> ```
> 
> in your next.config.js
> 
> Hope this would work for you

Tried this getting an error 
Please check your InjectManifest plugin configuration:
"offlineGoogleAnalytics" is not a supported parameter.

Any way we can support GA offline
