### ISSUE TITLE
How to hide "SW registered" message in production?

### ISSUE THREAD

**Issue by nghiepit** [hanford/next-offline#144]
Hi guys,

Thank you for your contribution.
I have a small question, How to hide "SW registered" message in production?

![image](https://user-images.githubusercontent.com/4768095/57980366-ffdc9b00-7a54-11e9-8f1b-123b477c354a.png)

**Comment by hanford** [comment]
@nghiepit currently dont have support for this, we could add a `verbose` flag in the plugin that hides the message if `verbose` is false though.

Would merge a PR around that if you think it'd be helpful

**Comment by hanford** [comment]
Going to close this due to inactivity. If you'd like to change this functionality please submit a PR!
