### ISSUE TITLE
networkFirst Depreacted

### ISSUE THREAD

**Issue by rauleite** [hanford/next-offline#146]
Hey, thank you for your work, it helps me.

On build time:

_Specifying 'networkFirst'' in a 'runtimeCaching[].handler' option is deprecated. Please update your config to use 'NetworkFirst' instead. In v4 Workbox strategies are now classes instead of functions._

According to the [migration guide](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3), just update examples from ['networkFirst'](https://github.com/hanford/next-offline/blob/master/examples/now2/next.config.js#L11) to 'NetowrkFirst'.

**Comment by hanford** [comment]
Thanks @rauleite 

If you'd like to a PR you can, otherwise I'll probably update it this weekend.

**Comment by rauleite** [comment]
Hy @hanford 

I did it. If anything happens, let me know.

**Comment by hanford** [comment]
thanks for the contribution @rauleite !
