### ISSUE TITLE
home page (document type) is not cached

### ISSUE THREAD

**Issue by mydearxym** [hanford/next-offline#149]
hello there ~

i am using this awesome next-offline on [my side project](https://github.com/coderplanets/coderplanets_web), the online address is [here](https://coderplanets.com/home/posts)

everything woks fine except the home page, which is document type: 

![image](https://user-images.githubusercontent.com/6184465/59106316-b3f08800-8968-11e9-9d37-0f9eb2a4f7f5.png)

the offline config file is [here](https://github.com/coderplanets/coderplanets_web/blob/dev/config/next_offline.js), and default next.config.js is [here](https://github.com/coderplanets/coderplanets_web/blob/dev/next.config.js#L73)

so what is the this document file ? and why is not be cached by serviceWorker ?

**Comment by hanford** [comment]
After visiting it and disabling my network connection things worked for me. Can you provide some more information?

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/2148168/59296018-d66cf480-8c39-11e9-8b28-8d2111c60a8c.png">

**Comment by mydearxym** [comment]
@hanford thanks for the reply ~

i was expect the initial page is cached by the service worker so i can visit the site even is offline

**Comment by hanford** [comment]
because you're site is on `/home/posts` you might need to adjust the `scope` of your service worker: 

Service worker scope information:
https://stackoverflow.com/a/35780776

how to modify scope w/ next-offline:
https://github.com/hanford/next-offline#next-offline-options

**Comment by mydearxym** [comment]
thanks, but the default scope  is set to '/',  is that mean next-offline will only cache the resource with _next prefix,  like: _next/some-script.xx  ?
