### ISSUE TITLE
Can we get improved example in doc ?

### ISSUE THREAD

**Issue by ScreamZ** [hanford/next-offline#150]
Hello,

I'm trying to build a simple PWA using next-offline.

The documentation isn't talking about how to deal with `manifest.json` and I see many different ways to deal with it. Not sure which one is cool.

That's why I think it could be a nice idea that you describe a complete workflow to achieve the setup :)

https://nextjs.org/features/progressive-web-apps is a bit simple and seems not work anymore.

Thanks :)

**Comment by hanford** [comment]
added a section about serving the service worker which will hopefully reduce confusion

**Comment by ScreamZ** [comment]
@hanford Thanks for quickly reply :)

I'm using next as static site builder (using `next generate` and `next export`, i'm trying to get the thing as simple as possible.

The other thing is that i want to validate in development that the worker is working, so I changed some things to get this : 

```js
module.exports = withTypescript(
  withOffline({
    env: localEnv,
    workboxOpts: {
      swDest: "service-worker.js",
      runtimeCaching: [
        {
          urlPattern: /^http?.*/,
          handler: "NetworkFirst",
          options: {
            cacheName: "https-calls",
            networkTimeoutSeconds: 15,
            expiration: {
              maxEntries: 150,
              maxAgeSeconds: 30 * 24 * 60 * 60 // 1 month
            },
            cacheableResponse: {
              statuses: [0, 200]
            }
          }
        }
      ]
    }
  })
);
```

In terms of hosting i'm on a premise solution with an nginx behind SSL.

**I also added a manifest.json by hand in the `static`folder**
```json
{
  "short_name": "My own app",
  "name": "My app",
  "icons": [
    {
      "src": "https://placehold.it/128x128",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "https://placehold.it/144x144",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "https://placehold.it/152x152",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "https://placehold.it/192x192",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "https://placehold.it/256x256",
      "sizes": "256x256",
      "type": "image/png"
    }
  ],
  "start_url": "/",
  "display": "standalone",
  "background_color": "#172578",
  "theme_color": "#172578"
}
```

**Comment by hanford** [comment]
@ScreamZ I've added a new example which uses `next export`, and it seems to be working fine for me: https://github.com/hanford/next-offline/tree/master/examples/next-export

If you're still having trouble please open a new issue
