### ISSUE TITLE
warn in build time from workbox

### ISSUE THREAD

**Issue by straxico** [hanford/next-offline#153]
hi
when i build my project i see this warn. i use next-offline without any config and dont use globDirectory or globPatterns ... but i see this warn
```
Compiled with warnings.

You're using the following Workbox configuration options: [globDirectory, globPatterns]. In Workbox v3 and later, this is usually not needed. Please see https://goo.gl/EQ4Rhm for more info.
```

**Comment by hanford** [comment]
yeah, `next-offline` is using them.

We're benefiting from the functionality (more things are cached) so I'm tempted to leave it.

**Comment by hanford** [comment]
Going to go ahead and close this, once Workbox v5 is out we'll cut the next-offline v5 release and this will go away.
