### ISSUE TITLE
Example for Now 2 not pointing to correct service worker

### ISSUE THREAD

**Issue by arrel** [hanford/next-offline#154]
The [example for now2](https://github.com/hanford/next-offline/tree/master/examples/now2) does not work out of the box because:
1. the service worker is auto-generated in the `/static` folder, but the default config sets `swDest: workboxOpts.swDest || 'service-worker.js',`
2. The next config target isn't set to `'serverless'`

I got it working by adding the below config options `next.config.js`
```
{
  target: 'serverless',
  workboxOpts: {
    swDest: 'static/service-worker.js'
  }
}
```

And here's an example repo w/ before and after:
https://github.com/arrel/next-offline-now-service-worker

I'm not sure if the correct solution is to update the default to `swDest: workboxOpts.swDest || 'static/service-worker.js',` or to just update the example, so have not created a PR. Let me know if you'd like one!

**Comment by ScreamZ** [comment]
And also it's good to know if this is specific to `now2` or also to any running environment like `nginx` static folder.

**Comment by ScreamZ** [comment]
https://github.com/hanford/next-offline/blob/master/examples/now2/now.json

AS we can see there is a specific redirection too

**Comment by hanford** [comment]
@arrel thanks for pointing out the serverless thing. 

Originally made the examples while now 2 was still extremely early and so things have changed slightly.

As for updating the example, I've updated and it can confirm it's working when deployed w/ now 2.0 - though I'm not 100% sure if it's working during development.

**Comment by edwinwebb** [comment]
I tried the example here https://github.com/hanford/next-offline/tree/master/examples/now2 and it didn't work offline. I replaced next.config.js with this file https://github.com/arrel/next-offline-now-service-worker/blob/master/next.config.js to have it work as expected.

**Comment by arrel** [comment]
@edwinwebb that's right. Without `swDest` set to point to the static folder the service worker file is generated in the `.next/` root but is not deployed.

I believe now creates lambdas for each page and copies the `/static` folder over, but does not deploy files in the root of `/.next` build folder.

**Comment by edwinwebb** [comment]
@arrel Found it a little surprising the example didn't work out of the box. Many thanks for the project. Very easy to use and great results.

**Comment by hanford** [comment]
thanks for the PR! Going to go ahead and close this now that I've merged it.

Feel free to open another issue if any of ya run into anything else.

**Comment by arrel** [comment]
Thx! That was fun.
