### ISSUE TITLE
Original Workbox Manifest File Being Imported By SW

### ISSUE THREAD

**Issue by derekdowling** [hanford/next-offline#156]
## Bug 🐞

Version: Next-Offline 4.0.2

**What happens:**

When using a custom `importsDirectory` in `workboxOpts` with `generateSw: true`, the original SW precache manifest file generated by Workbox is still being requested in the Service Worker file from a an `importScripts` invocation line that looks something like:

```
importScripts(
  "_next/static/sw/precache-manifest.d6eae43349fcf30893a45d2d8b5ef9a3.js"
);
```

The pre-cache assets as listed in the file generated by Workbox are not prefixed properly for Next. So when that file is imported and those files are fetched, they 404 causing the Service Worker to crash.

**Expected:**

The `importScripts` call that is added to the SW file by Workbox should be removed from the file so that non-valid paths aren't fetched and 404 causing the SW to crash.
```
importScripts(
  "_next/static/sw/precache-manifest.d6eae43349fcf30893a45d2d8b5ef9a3.js"
);
```

Manually removing this line from the output SW file causes pre-caching to work as expected.

**Comment by derekdowling** [comment]
Is there a reason why next-offline couldn't utilize one of Workbox's existing fields to apply the necessary `_next` prefix to pre-cache assets. I'm thinking specifically of `modifyURLPrefix` or `manifestTransforms` as seen [here](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)?

**Comment by derekdowling** [comment]
Looks like there is going to be a breaking change with Workbox v5 with regards to Next-Offline's precaching strategy: https://github.com/GoogleChrome/workbox/issues/1774#issuecomment-507819065.

**Comment by hanford** [comment]
@derekdowling I believe at the time, (workbox 2 or 3) when most of the initial development was done, those features either didn't exist or I simply didn't know about them.

I'd be happy to lean on them (entirely, if possible) and remove the parts of next-offline that manually achieving this.

Would you be interested in doing a PR? My primary focus when I work on this plugin (hoping to get a few hours in this weekend) will be enhancing the development mode experience.

Thanks for the tip, I'd love for workbox to do more of the heavy lifting here.

**Comment by derekdowling** [comment]
> I believe at the time, (workbox 2 or 3) when most of the initial development was done, those features either didn't exist or I simply didn't know about them.

@hanford, yup, that's what I suspected 😆. I should be able to take a crack at this. Unfortunately it looks like this is going to require getting to Workbox 5 first. How do you feel about me bundling in that with this work and then cutting this as a next-offline v5 Alpha to match?

**Comment by hanford** [comment]
Sounds great!

**Comment by hanford** [comment]
@derekdowling let me know once you begin working on this, will likely use your branch as my base for the development mode work I'll do. (that way we don't step on each others toes with the v5 upgrade).

**Comment by derekdowling** [comment]
@hanford https://github.com/hanford/next-offline/pull/158 🎉
