### ISSUE TITLE
404 on /_next/main.js

### ISSUE THREAD

**Issue by TonyBrobston** [hanford/next-offline#157]
- Issue and steps to reproduce.
    When the service worker is registered one of the items in the `precacheManifest` returns a 404 when requested. I can't provide the repo but may be able to come up with a code sample later to reproduce, I assume it will be difficult but I could give it a shot.
- Versions: 
    I've tried 7.0.2 and 9.0.1 of `next` with 4.0.2 of `next-offline`
- Screenshots.
    Here is the 404:
![image](https://user-images.githubusercontent.com/4724577/61157163-f1da5200-a4ba-11e9-9774-c76c1210099e.png)

- Expected.
    I would expect the service worker to register and I'm not sure what should occur with the failed promise. This is where I'm looking for some advice. I'm not familiar enough with `next` and `next-offline` to understand what `/_next/main.js` does. Maybe we can talk through this.

- Actual.
    Here is the error I get:
```
SW registered:  ServiceWorkerRegistration {scope: "https://[redacted].com/", updateViaCache: "imports", active: null, installing: ServiceWorker, navigationPreload: NavigationPreloadManager, …}
PrecacheController.mjs:194 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://[redacted].com/_next/main.js?__WB_REVISION__=ded8378b7df01f45c72c","status":404}]
    at l.o (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1749)
    at async Promise.all (index 0)
    at async l.install (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1221)
```
- Browser name and version.
    Chrome version: 75.0.3770.100

I see in the `service-worker.js` that `self.__precacheManifest` object has `{
  "url": "/_next/main.js",
  "revision": "ded8378b7df01f45c72c"
}` inside of it. Which presumably is why the call occurs that fails with a 404.

I sort of wonder what would occur if `self.__precacheManifest` was not looking for `/_next/main.js`, would it fail because it's missing this resource or would it succeed because it didn't have an uncaught promise?

I'm pretty stumped on this one, any help is much appreciated.

**Comment by hanford** [comment]
Can you provide an example repo with some steps where I can easily reproduce this error?

**Comment by derekdowling** [comment]
This might be related to: https://github.com/hanford/next-offline/issues/156.

**Comment by TonyBrobston** [comment]
@derekdowling It seems to be expecting `main.js` at `https://[removed url].com/_next/main.js?__WB_REVISION__=ded8378b7df01f45c72c`.

When I navigate to that url I get:
![image](https://user-images.githubusercontent.com/4724577/61249454-e2f1da80-a71a-11e9-82c1-8da156367b98.png)

I read your issue: https://github.com/hanford/next-offline/issues/156 and it seemed very similar.

@hanford I'll read through @derekdowling's issue a bit more when I have some time (maybe tonight or tomorrow) and if it's unrelated I'll look into creating an example repo.

Thanks for the help so far!

**Comment by TonyBrobston** [comment]
@derekdowling I re-read your question and think I misinterpreted it. I don't entirely understand how `next` serves up some of these files. Are you asking what url I expect `main.js` to be served from? Initial my answer is that I don't know, I can try to determine that. I'll have to look more into how `next` serves files to understand where `main.js` originates from.

**Comment by ahmadawais** [comment]
I have a similar issue. 

When I deploy a new build the site fails to load.

![](https://on.ahmda.ws/363693/c)

Looks like the while the `service-worker.js` file does get updated but the HTML of index.html still has the old version of JS files.

E.g. in the `https://domain.dev/service-worker.js` I have this

```js

  | self.__precacheManifest = [
-- | --
  | "/",
  | {
  | "url": "/_next/static/ODQIzX9GUJEoIn9B-KQt5/pages/_app.js",
  | "revision": "194dfb3e8d2054867f6c"
  | },
  | {
  | "url": "/_next/static/ODQIzX9GUJEoIn9B-KQt5/pages/_error.js",
  | "revision": "83701e80a581631e9367"
  | },
  | {
  | "url": "/_next/static/ODQIzX9GUJEoIn9B-KQt5/pages/demo.js",
  | "revision": "0d0af8505f8776de9062"
  | },
  | {
  | "url": "/_next/static/ODQIzX9GUJEoIn9B-KQt5/pages/for/context.js",
  | "revision": "9756fa0906b5f90ab467"
  | },
  | {
  | "url": "/_next/static/ODQIzX9GUJEoIn9B-KQt5/pages/index.js",
  | "revision": "a26db410e25a3e4b1851"
  | },
  | {
  | "url": "/_next/static/chunks/commons.df20c05471f39c6bf772.js",
  | "revision": "9323754fe8b3e04fde6b"
  | },
  | {
  | "url": "/_next/static/runtime/main-683804724884cfdef4bf.js",
  | "revision": "08dfecf06bad2537f794"
  | },
  | {
  | "url": "/_next/static/runtime/webpack-3df6523e264ff2ac6548.js",
  | "revision": "b0a559ac8f238b6fd6f7"
  | }
  | ];

```

But on the site's HTML it's still loading the old files which are 404.

```html
href="/_next/static/9OQjr8tmahlLq2nFoQ2fh/pages/index.js" as="script"/><link rel="preload" href="/_next/static/9OQjr8tmahlLq2nFoQ2fh/pages/_app.js" as="script"/><link rel="preload" href="/_next/static/runtime/webpack-3df6523e264ff2ac6548.js" as="script"/><link rel="preload" href="/_next/static/chunks/commons.045ebaf195f88e8db679.js" as="script"/><link rel="preload" href="/_next/static/runtime/main-683804724884cfdef4bf.js" as="script"/></head><body><div id="__next"><style data-emotion-css="9zpy8b">.css-9zpy8b{display:table;width:100%;backgro
```

HELP!

**Comment by ahmadawais** [comment]
Here's my config:

```js

const nextJSConfig = {
	target: 'serverless',
	transformManifest: manifest => ['/'].concat(manifest), // add the homepage to the cache
	workboxOpts: {
		swDest: 'static/service-worker.js',
		cleanupOutdatedCaches: true,
		runtimeCaching: [
			{
				urlPattern: '/',
				handler: 'StaleWhileRevalidate',
				options: {
					cacheName: 'html-cache',
					cacheableResponse: {
						statuses: [200],
					},
				},
			},
			{
				urlPattern: new RegExp('^https://api.domain.dev/*.json'),
				handler: 'NetworkFirst',
				options: {
					cacheName: 'api-cache',
					cacheableResponse: {
						statuses: [200],
					},
				},
			},
			{
				urlPattern: /.*\.(?:eot|woff|ttf)/,
				handler: 'CacheFirst',
				options: {
					cacheName: 'font-cache',
					expiration: {
						maxEntries: 150,
						maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month.
					},
					cacheableResponse: {
						statuses: [0, 200],
					},
				},
			},
			{
				urlPattern: /.*\.(?:png|webp|jpg|jpeg|svg|gif)/,
				handler: 'CacheFirst',
				options: {
					cacheName: 'image-cache',
					expiration: {
						maxEntries: 150,
						maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month.
					},
					cacheableResponse: {
						statuses: [0, 200],
					},
				},
			},
		],
	},
};
```

and `now.json` for monorepo with site Next.js in `www` dir.

```json
{
			"src": "/service-worker.js",
			"dest": "/www/_next/static/service-worker.js",
			"headers": {
				"Service-Worker-Allowed": "/"
			}
		}
```

**Comment by TonyBrobston** [comment]
@ahmadawais As you mentioned, seems like a caching issue. I'm not familiar with how you bust the cache. Maybe @hanford can clarify or point us towards some documentation?

As for my issue, I basically solved the `/_next/main.js` issue the same way I solved the `/service-worker.js` issue. We're using hapijs so I could follow the example, but used it for reference:

serving `/service-worker.js`:
```js
const path = require('path');

const getServiceWorkerRoute = {
    handler: async (request, h) => h.file(path.join(`${__dirname}/../../`, '.next', '/service-worker.js')),
    method: 'GET',
    path: '/service-worker.js'
};

module.exports = [
    getServiceWorkerRoute
];
```

serving `/_next/main.js`:
```js
const path = require('path');

const getMainJsRoute = {
    handler: async (request, h) => h.file(path.join(`${__dirname}/../../`, '.next', '/main.js')),
    method: 'GET',
    path: '/_next/main.js'
};

module.exports = [
    getMainJsRoute
];
```

Feels like a hack, but the 404 is gone, the service worker registers just fine, and now offline mode works. I'll go with this for now.

**Comment by ahmadawais** [comment]
@TonyBrobston probably. For my case issue was that severe — I just removed the PWA from Next.js and not happy about it.

**Comment by TonyBrobston** [comment]
I'm going to go ahead and close this as I think I got mostly where I wanted to, however the work I was doing is sort of on hold.
