### ISSUE TITLE
Spread Syntax Error

### ISSUE THREAD

**Issue by kevinpmiller** [hanford/next-offline#16]
I recently installed the plugin and when I try to start my server I get the following error. Any ideas? My first thought was that I was missing something but I don't believe that's the case.

Thanks for taking a look!

next.config.js
------
const withCSS = require('@zeit/next-css')
const initReactFastclick = require('react-fastclick')
const withOffline = require('next-offline')

initReactFastclick()

module.exports = {
  // Other webpack config...
  plugins: [
    new withCSS(),
    new withOffline()
  ]
};

package.json
------
{
  "main": "index.js",
  "repository": "__private",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node server.js",
    "prod": "next build && NODE_ENV=production node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "keywords": [],
  "author": "Kevin Miller",
  "license": "ISC",
  "dependencies": {
    "@zeit/next-css": "^0.1.5",
    "express": "^4.16.3",
    "isomorphic-unfetch": "^2.0.0",
    "lscache": "^1.1.0",
    "next": "^5.1.0",
    "next-offline": "^2.3.1",
    "next-router-events": "^2.0.0",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-fastclick": "^3.0.2",
    "react-markdown": "^3.3.0",
    "render-if": "^0.1.1",
    "styled-components": "^3.2.5",
    "workbox-webpack-plugin": "^3.0.1"
  },
  "devDependencies": {
    "babel-preset-stage-0": "^6.24.1"
  }
}

Error
------
/Users/kevin/projects/test/node_modules/next-offline/index.js:6
  ...nextConfig,
  ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kevin/projects/test/next.config.js:3:21)
    at Module._compile (module.js:571:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kevin/.npm/_logs/2018-04-02T22_18_40_959Z-debug.log

**Comment by hanford** [comment]
@kevinpmiller What version of node are you using? I believe the rest/spread operator landed in Node 8.  I believe you can check by running `node -v`

**Comment by kevinpmiller** [comment]
@hanford That was exactly it, thanks! Everything appears to be working now but I have a question on the server.js file. I am using express for my server and the urls / and /search/:id don't seem to work offline. Below is my configuration, I think I need to re-arrange things a little, can you point me in the right direction?

Thanks for all of your help and let me know if I should create a new issue and close this one?

`const express = require('express')
const next = require('next')
const { join } = require('path')
const { parse } = require('url')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app
  .prepare()
  .then(() => {
    const server = express()

    server.get('/service-worker.js', (request, response) => {
      const parsedUrl = parse(request.url, true)
      const { pathname } = parsedUrl
      const filePath = join(__dirname, '.next', pathname)

      app.serveStatic(request, response, filePath)
    })

    // TODO: Add mapping based on current URL structure
    server.get('/search/:id', (request, response) => {
      app.render(request, response, '/search', { id: request.params.id })
    })

    server.get('*', (request, response) => {
      return handle(request, response)
    })

    server.listen(3000, (error) => {
      if (error) {
        throw error
      }

      console.log('> Ready on http://localhost:3000')
    })
  })
  .catch((exemption) => {
    console.error(exemption.stack)

    process.exit(1)
  })`

**Comment by hanford** [comment]
Going to close this because the original issue has been resolved. If you want you can create another with the above problem, but AFAIK with dynamic data, because `request.params.id` could be _anything_ it'll only work offline if the user has navigated to it at least once before.
