### ISSUE TITLE
Storage size is always increasing

### ISSUE THREAD

**Issue by aralroca** [hanford/next-offline#163]
I feel that something I'm doing wrong in my side. However, I didn't see a Slack community or other ways, so I prefer to ask directly here.

I just configured `withOffline` with the next config:

```js
const hasOfflineSupport = withOffline({
  workboxOpts: {
    globPatterns: ['static/**/*'],
    modifyURLPrefix: {
      static: `${STATIC_PREFIX}static`, // I use a different prefix
    },
    globDirectory: '.',
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'offlineCache',
          expiration: {
            maxEntries: 50,
            maxAgeSeconds: 30 * 24 * 60 * 60,
            purgeOnQuotaError: true,
          },
        },
      },
    ],
  },
  ...config,
})
```
With this I expect that the service worker caches all the static folder and then all the `https` GET requests (latest 50) with the `purgeOnQuotaError` to clean the cache when it exceed.

Nevertheless, looks that the storage size always is increasing!! Also after reloading the same page is increasing although all the resources are already cached...!

![image](https://user-images.githubusercontent.com/13313058/61664980-3a241c00-acd4-11e9-8253-6f527a2e8fb7.png)

And also I'm getting this error in my console:

![image](https://user-images.githubusercontent.com/13313058/61665443-4a88c680-acd5-11e9-9281-50360ddd3bd5.png)

Does somebody know what I'm doing wrong?

**Comment by omaralbeik** [comment]
Having the same problem +1

**Comment by kasterlod** [comment]
@aralroca @omaralbeik hello! I had the same problem.

I fixed it by edit `urlPattern` to cache only requests, with default pattern it's caching everything, but seems like we don't need it. Thanks of that I decreased cache size from 1000+mb to about 25mb.
In my opinion with default pattern, images was cached twice or even more, and because of that there was such huge size of cache.

Please let me know if it help :D

**Comment by omaralbeik** [comment]
> @aralroca @omaralbeik hello! I had the same problem.
> 
> I fixed it by edit `urlPattern` to cache only requests, with default pattern it's caching everything, but seems like we don't need it. Thanks of that I decreased cache size from 1000+mb to about 25mb.
> In my opinion with default pattern, images was cached twice or even more, and because of that there was such huge size of cache. To optimise images, use next-optimized-images, it's working great.
> 
> Please let me know if it help :D

Thank you @kasterlod!
Could you please share the part where you define `urlPattern` to cache only requests

**Comment by kasterlod** [comment]
based on your's part of code:
`runtimeCaching: [
      {
        urlPattern: /^https?.*api/, -> *here put regex which matches only your api*
        handler: 'CacheFirst', -> *let's use cache first, you'll like it*
        options: {
          cacheName: 'offlineCache',
          expiration: {
            maxEntries: 50,
            maxAgeSeconds: 30 * 24 * 60 * 60, -> * you need to think how often your data will be updated, after expiration, cache will be refetched*
            purgeOnQuotaError: true,
          },
        },
      },
    ],`

**Comment by omaralbeik** [comment]
Thank you @kasterlod!

**Comment by hanford** [comment]
Going to close this out, feel free to reopen if you have additional questions!
