### ISSUE TITLE
Consider Converting To Mono-Repo

### ISSUE THREAD

**Issue by derekdowling** [hanford/next-offline#164]
This is a big ask, but converting all of the examples, tests, and actual plugin to be part of a single monorepo via something like Yarn workspaces would make local development much simpler.

The current flow requires an awkward blend of developing, using `yarn link` and then doing a version bump to a specific commit. This also would make CI considerably easier/faster if that became a priority in the future.

**Comment by hanford** [comment]
yeah, definitely would like to do this.

the tests/examples situation is far from ideal, I can probably swing this over the next day or two. I've got some monorepos that I can use as a template

**Comment by hanford** [comment]
Click around this branch and let me know what you think @derekdowling 

I had been meaning to do this for a while!

**Comment by derekdowling** [comment]
Looks great 🎉
