### ISSUE TITLE
Check for update and show refresh modal to user?

### ISSUE THREAD

**Issue by lolcoolkat** [hanford/next-offline#174]
I'd like to implement some custom ServiceWorker code that will check if the Service Worker has been updated and if so; show a modal to the user so they can refresh.

I tried to set the `swSrc` parameter in `workboxOpts` and `generateSw` to false but I was getting errors about `runtimeCaching` not being a valid parameter.

Thanks for any help!

**Comment by ardeaf** [comment]
Did you figure this out?
