### ISSUE TITLE
Custom serviceworker.js path

### ISSUE THREAD

**Issue by Astrantia** [hanford/next-offline#178]
Hi. Tried to search all of this project's github, but couldn't find anything that could help me. I have dynamic routes on /* and I'm not using server to fully control it. So my app thinks /service-worker.js is a normal page, not an asset. I'd like to be able to configure next-offline to generate SW in /static, and look for it in /static/ too. Is this achievable currently? I looked in swDest and swSrc, played with them, but couldn't make them work.

**Comment by hanford** [comment]
what version of `next-offline` are you using @Astrantia?

**Comment by Astrantia** [comment]
> what version of `next-offline` are you using @Astrantia?

Using `    "next-offline": "^4.0.3" `

**Comment by lolcoolkat** [comment]
Hey @Astrantia this is my next-offline config:

```
module.exports = {
  generateSw: false,
  workboxOpts: {
    swSrc: './utils/workbox/sw.js',
    swDest: 'static/sw.js',
    exclude: [/.+error\.js$/, /\.map$/],
  },
}
```

When you're making your custom `sw.js` file.. don't place it into the `/static` folder. Put it in a different folder. That way next-offline can put the compiled service worker into the static folder itself (with the destination you choose.

I am using Zeit Now with next-offline so I have to set a custom route rule for my service worker:

```
    {
      "src": "^/sw.js$",
      "dest": "/_next/static/sw.js",
      "headers": {
        "cache-control": "max-age=0",
        "Service-Worker-Allowed": "/"
      }
    }
```

If you give me a little bit more information on your use case; I can try and help further!

**Note**: There is a bug that I found when starting with next-offline that does not let you set the `swSrc` option in the next-offline config https://github.com/hanford/next-offline/issues/175#event-2548300960. It's been fixed and will be able in `5.0.0-beta.3`!

**Comment by Astrantia** [comment]
> If you give me a little bit more information on your use case; I can try and help further!

Thanks for the insightful response. That now.json doesn't work with now2 so I've edited it into
```
{
    "routes": [
        {
            "src": "^/sw.js$",
            "dest": "/_next/static/sw.js",
            "headers": {
                "cache-control": "max-age=0",
                "Service-Worker-Allowed": "/"
            }
        }
    ]
}
```

Upgraded to beta too, but failed deploy on this error

Failed to compile.
```
Entry module not found: Error: Can't resolve './utils/workbox/sw.js' in '/tmp/150a895e'
```
For my use case, I don't want to have a custom service worker.js file, I only want to make my app installable, so I don't have a custom SW.

**Comment by lolcoolkat** [comment]
@Astrantia that wasn't my entire `now.json` config I was posting.. just a part of it :P Can you share your next-offline config?

**Comment by Astrantia** [comment]
> @Astrantia that wasn't my entire `now.json` config I was posting.. just a part of it :P Can you share your next-offline config?

I tried to copy your approach directly :laughing: 
```
  generateSw: false,
  workboxOpts: {
    swSrc: './utils/workbox/sw.js',
    swDest: 'static/sw.js',
    exclude: [/.+error\.js$/, /\.map$/],
  }
```
Perhaps I should set `generateSw: true`?

**Comment by lolcoolkat** [comment]
@Astrantia No I was mistaken; I thought you wanted to use a custom service worker with next-offline. You should be using https://github.com/hanford/next-offline/blob/master/packages/now2-example/next.config.js. I just tried deploying the now-2 example and it worked fine.

**Comment by lolcoolkat** [comment]
Also @Astrantia NextJS does not think that `/service-worker.js` is a page :P It's only showing up on `/service-worker.js` because that's what's defined in your `now.json` file. If you want to have your service worker show up on another url do the following.

**Line 6 of now.json**
```
"src": "^/sw/service-worker.js$",	
```

Line 10 of next.config.js
```
swDest: 'static/sw/service-worker.js',
```

**Comment by Astrantia** [comment]
> Also @Astrantia NextJS does not think that `/service-worker.js` is a page :P It's only showing up on `/service-worker.js` because that's what's defined in your `now.json` file. If you want to have your service worker show up on another url do the following.
> 
> **Line 6 of now.json** in the now2-example repo
> 
> ```
> "src": "^/sw/service-worker.js$",	
> "dest": "/_next/static/sw/service-worker.js",
> ```
> 
> **Line 10 of next.config.js** in the now2-example repo
> 
> ```
> swDest: 'static/sw/service-worker.js',
> ```
> 
> If you deploy and go to `https://yoursite.com/sw/service-worker.js` you should see it there now instead. 

Thank you so much for following me through this :bowing_man: , I've got it working now. Sorry to open an issue that was not an issue at all. :disappointed:
