### ISSUE TITLE
When using `next export`, static assets are duplicated and pre-cached wrongly

### ISSUE THREAD

**Issue by simonsinclair** [hanford/next-offline#182]
### Overview
For readability I am referring to `.next/` as the build directory and `out/` as the public directory.

When you `next export` a project, `build/static` is not copied to `public/static` – it is copied to `public/_next/static`. These directories are not the same as the **project** `static` directory where, for example, a user might [serve images](https://nextjs.org/docs#static-file-serving-eg-images). However:

### Issue
`next-offline@beta` currently copies everything from the **project** `static` directory into `build/static` and generates a pre-cache manifest.

**This creates two issues:**
1. Duplication. Everything in `public/static` is also in `public/_next/static`.
2. Files sourced from `public/static` in your app aren't pre-cached by the SW.

### Notes
Copying the **project** `static` directory to a temporary directory which isn't used by Next and then rewriting the URLs in the pre-cache manifest the same way we do for `_next/static/` fixes this.
```
new CopyPlugin([{
  from: 'static',
  to: 'temp-static',
}]),
new GenerateSW({
  ...
  modifyURLPrefix: {
    'static/': '_next/static/',
    'temp-static/': 'static/',
  },
  ...
})
```
As a bonus, Next doesn't touch `build/temp-static` so it isn't added to `public` on export, which also fixes the duplication.

**Comment by hanford** [comment]
@simonsinclair can you share which version of next-offline you're using?

**Comment by hanford** [comment]
Hmmmm, interesting 🙇‍♂️

So in the beta, we're trying to move some of the heavy lifting over to workbox and this might be a new regression.

Can you share if this is working as expected in version 4?
