### ISSUE TITLE
generateNextManifest runs before workbox-webpack-plugin finishes

### ISSUE THREAD

**Issue by sarneeh** [hanford/next-offline#185]
Hey @hanford! I'm sorry but it seems that I've tested my recent PR (#183) incorrectly and it did not change anything. I've misunderstood the `webpack` hook API.

What we need to do is to hook on [afterEmit](https://webpack.js.org/api/compiler-hooks/#afteremit) instead of [done](https://webpack.js.org/api/compiler-hooks/#done), as `done` runs after compilation, which - by testing those solutions - seems that does not mean, that the files have been written to the filesystem.

Again, I'm sorry for this confusion. I'll introduce a PR with a fix in a moment.

**Comment by hanford** [comment]
released the fix in v4.0.5!
