### ISSUE TITLE
Current page does not respond with a 200 when offline 

### ISSUE THREAD

**Issue by thathurtabit** [hanford/next-offline#187]
Hi there, firstly thanks for your work with this plugin and thanks for any help to point me in the right direction here.

I'm 95% sure this problem I'm facing is due to my setup, as it *is* registering the service worker, but the service worker doesn't seem to work when offline.

"Current page does not respond with a 200 when offline." 

You can view the live site here (see after running a lighthouse audit): https://fretmap.app

Below is a link to some of my setup. My main app is on a private repo at the moment, but I can grant access if request.

Thank you.

**package.json**
https://gist.github.com/thathurtabit/55a8edac1cef20970990ef2a01deee64

**next.config.js**
https://gist.github.com/thathurtabit/dde117a666bf493c79311d4fcdf20f7a

**server.js**
https://gist.github.com/thathurtabit/9f6a834b381dc2fbfe1d76cb30b60b45

**Comment by SiroDiaz** [comment]
@thathurtabit are you sure that the service worker is been served with `res.sendFile`? i tried it but i get an error saying that res.sendFile is not a function. I have a very similar setup.

**Comment by talentedandrew** [comment]
@thathurtabit This might be because of the 'start_url' and 'scope', mentioned in your `manifest.json` file. Can you share your `manifest.json` file?

OR

`swDest: 'static/service-worker.js'` in your `next.config.js` is relative to the webpack output path.

Change it to `swDest: 'service-worker.js'` and also change the express GET handler  from `return res.sendFile(__dirname + '/static/service-worker.js');` to `return res.sendFile(__dirname + '.next' + '/service-worker.js');`

**Comment by Tirex04** [comment]
I am having same issue
Current page does not respond with a 200 when offline

static/manifest.json
`
...
"background_color": "#777777",
  "display": "standalone",
  "orientation": "portrait",
  "Scope": "/",
  "start_url": "/",
...icons
`

server.js
`
const { createServer } = require('http')
const { join } = require('path')
const { parse } = require('url')
const next = require('next')

const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handle = app.getRequestHandler()

app.prepare()
    .then(() => {
        createServer((req, res) => {
            const parsedUrl = parse(req.url, true)
            const { pathname } = parsedUrl

            // handle GET request to /service-worker.js
            if (pathname === '/service-worker.js') {
                const filePath = join(__dirname, '.next', pathname)

                app.serveStatic(req, res, filePath)
            } else {
                handle(req, res, parsedUrl)
            }
        })
            .listen(3000, () => {
            })
    })
`

**Comment by tiotdev** [comment]
I had the same problem. Turns out that the default caching strategies are overwritten when using custom workboxOpts. Changing

```
workboxOpts: {
          importScripts: ['./scripts/sw-push-listener.js'],
        }
```

to

```
workboxOpts: {
          runtimeCaching: [
            {
              urlPattern: /^https?.*/,
              handler: 'NetworkFirst',
              options: {
                cacheName: 'offlineCache',
                expiration: {
                  maxEntries: 200,
                },
              },
            },
          ],
          importScripts: ['./scripts/sw-push-listener.js'],
        },
```

did the trick for me

**Comment by hanford** [comment]
Is this good to close?

**Comment by dryleaf** [comment]
@thathurtabit Could you please tell us how you fixed the issue?

**Comment by thathurtabit** [comment]
Sorry folks, I lost track of this. I think I ended up using https://github.com/shadowwalker/next-pwa in my app - although the above responses may well fix the above issue.
