### ISSUE TITLE
I got this message when npm run build

### ISSUE THREAD

**Issue by x4080** [hanford/next-offline#194]
```
You're using the following Workbox configuration options: [globDirectory, globPatterns]. In Workbox v3 and later, this is usually not needed. Please see https://goo.gl/EQ4Rhm for more info.

One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": ".",
  "globPattern": "static/**/*",
  "globIgnores": [
    "**/node_modules/**/*"
  ]
```

Is this normal ? 

Thanks

**Comment by Koen028** [comment]
Are you using the new Next.js 9.1 feature: `public` folder?

**Comment by hanford** [comment]
@x4080 we're also going to release next-offline version 5 soon, which fixes this

**Comment by x4080** [comment]
@Koen028 Yes

@hanford  Thanks

**Comment by hanford** [comment]
@x4080 please feel free to try the 5.0.0-beta and let me know if it's still happening, going to go ahead and close this as it'll be fixed in the next version we release

**Comment by x4080** [comment]
Yes it works now, thanks !
