### ISSUE TITLE
Question : best practice for versioning ?

### ISSUE THREAD

**Issue by x4080** [hanford/next-offline#198]
Hi @hanford 

Is there best practice for versioning ? If we change the pages of next js and upload to server, what should we do to refresh the cache already in client's pwa ?

I tested and when I refreshed the client, it will load the latest version, is this the way ?

Thanks

**Comment by hanford** [comment]
That's what I do!

**Comment by hanford** [comment]
Going to go ahead and close this, because I don't think it's an issue, feel free to open another issue if you run into anything

**Comment by x4080** [comment]
Thanks @hanford

**Comment by MistaPidaus** [comment]
Hi @hanford. I've noticed that once I updated some of my components, didn't change immediately. I've refresh the client/browser but remain the same. I've checked that there's a service worker that is waiting to activate. Is there a way to trigger this? or just automatically skipWaiting? 

Thanks

**Comment by kishanio** [comment]
@hanford service workers on safari don't update upon client being updated.
