### ISSUE TITLE
Homepage not in cached after initial visit

### ISSUE THREAD

**Issue by gerhardsletten** [hanford/next-offline#2]
hi @hanford 

Much like you, I have a similar site like jackhanford.com, but one thing that bothers me is when a new user enters the site, the homepage will not be in cache after just one visit to the site. You will need to do a full reload, or a secondary visit before the homepage will work when offline.

Do you have any suggestions on this issue?

**Comment by hanford** [comment]
@gerhardsletten interesting, can you give me more information about what browser / OS / url / etc

**Comment by hanford** [comment]
@gerhardsletten interesting I noticed this too while playing around with my website on incognito. I'm not certain why, i can spend some time on Monday looking a little deeper.

**Comment by gerhardsletten** [comment]
Hi @hanford 

The default config is opting of of using `sw-precache` since all next-assets are to be ignored. Instead it utilize `sw-toolbox` caching, and this will start after the service-worker is installed. You can see it in the Application > Cache in devtools that the sw-precache si empty.

```js
{
  verbose: false,
  minify: true,
  staticFileGlobsIgnorePatterns: [/\.next\//],
  runtimeCaching: [
    {
      handler: 'networkFirst',
      urlPattern: /^https?.*/
    }
  ]
}
```
Also if you inspect the generated service-worker.js script the `precacheConfig` is an empty array. With e.g. create-react-app the same var will be something like this:

```js
var precacheConfig=[["/index.html","cef06143bd734e39a03a769077b815dc"],["/static/css/main.c17080f1.css","302476b8b379a677f648aa1e48918ebd"],["/static/js/main.ee7b2412.js","6324b1d1d8cdf43f23be87809e68868e"],["/static/media/logo.5d5d9eef.svg","5d5d9eefa31e5e13a6610d9fa7a283bb"]]
```

So to gain immediately offline support, we would need to place the next's assets in this list, and with this `staticFileGlobs` option they should be picked up by `sw-precache-webpack-plugin`:

```
staticFileGlobs: [
  '**/.next/bundles/pages/*.js',
  '**/.next/chunks/**/*.js',
  '/manifest.json',
  '**/.next/app.js',
  '/'
],
```
Resulting in this:

```
var precacheConfig = [[".next/app.js","cb8667b50eb9e4cdf1929a060d99a42c"],[".next/bundles/pages/_document.js","48c3a350f4235d869f3c9c08caaeefd4"],[".next/bundles/pages/_error.js","29d4be00a8407bf6021b1f1b486184f4"],[".next/bundles/pages/index.js","8d008b6a0757928557bde9d0378620fa"],[".next/bundles/pages/page.js","12e52b1f55b13ffe0c710c89169582a4"],[".next/bundles/pages/portfolios.js","5a87112b26c97882152591a5baef295a"],[".next/bundles/pages/services.js","c6bfcde6f56da47fbe43a0eba0fcba96"],[".next/bundles/pages/technologies.js","510be2154889872264a6d75709bc79d1"],[".next/chunks/components_HomePage_86ac2dcc6d50b1f20a7b1dbb88502a2d.js","fc12bcc0d4b18099c8d42d17717b6304"],[".next/chunks/components_Page_41af8f4d62fa02427036718c5cad573b.js","be1671cc9f9fc35b8a2a8fae30d6c676"],[".next/chunks/components_Portfolios_86a88974b3b03783f8fc5c6b0d32b70e.js","b7373ac65a32b3f27938e93fd51fc83b"],[".next/chunks/components_Services_a8ec6157c551f020ec4efde057b27105.js","92831bb79306b544a55dac62a8b504db"],[".next/chunks/components_Technologies_5edfeab2e3bb3d0c2478ce08c3ac80fd.js","625a32483a26c2696387b88e096b6a69"]];
```

But the problem is that next serve these in another way so we would like is to do a complete rewrite of how their urls should be, like how [the Ran-starter is doing with Offline-plugin here](https://github.com/Sly777/ran/blob/master/next.config.js#L43), but `sw-precache-webpack-plugin` do not support something similar so this is where I am now.

**Comment by hanford** [comment]
@gerhardsletten going to close in favor of #3
