### ISSUE TITLE
now2-example dosen't work 

### ISSUE THREAD

**Issue by codifius** [hanford/next-offline#201]
when i download [now2-example](https://github.com/hanford/next-offline/tree/master/packages/now2-example) from the repository and i made :

- npm install
- npm build
- npm start

I have an error : "Failed to register a ServiceWorker for scope" in the console when i lunch the app in localhots:3000

**Comment by bcjohnblue** [comment]
I meet the same problem too.

**Comment by allenylzhou** [comment]
I just updated to next-offline@5.0.0-beta.9 and I am still experiencing this.
The reason for the error is that it `localhost:3000/service-worker.js` is returning a 404. Do we have to manually create the file or change something in the config?
```
SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
```

My config:
```
// Do not use next-css!
// https://github.com/zeit/next-plugins/issues/282
const withOffline = require("next-offline");
const withImages = require("next-images");

const nextConfig = {
  target: 'serverless',
  transformManifest: manifest => ['/'].concat(manifest), // add the homepage to the cache
  // Trying to set NODE_ENV=production when running yarn dev causes a build-time error so we
  // turn on the SW in dev mode so that we can actually test it
  generateInDevMode: true,
  workboxOpts: {
    swDest: 'static/service-worker.js',
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'https-calls',
          networkTimeoutSeconds: 15,
          expiration: {
            maxEntries: 150,
            maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month
          },
          cacheableResponse: {
            statuses: [0, 200],
          },
        },
      },
    ],
  },
};

module.exports = withOffline(withImages(nextConfig));
```

**Comment by ShanonJackson** [comment]
Pretty sure its because you have to deploy it, as this works along side the routes configuration in now.json

**Comment by codifius** [comment]
@ShanonJackson thanks it works when I deployed it.

**Comment by defrex** [comment]
So, we're supposed to tolerate the error in local dev? How do we test it?

**Comment by ShanonJackson** [comment]
you test it in staging

**Comment by defrex** [comment]
Well, for future reference, I solved it locally. 

I simply made a symlink from `public/service-worker.js` to `.next/static/service-worker.js`, then added `public/service-worker.js` to `.gitignore`.

```sh
cd public
ln -s ../.next/static/service-worker.js .
cd ..
echo "/public/service-worker.js" >> .gitignore
```
