### ISSUE TITLE
Update service worker

### ISSUE THREAD

**Issue by MistaPidaus** [hanford/next-offline#202]
Reference issue: https://github.com/hanford/next-offline/issues/198#issuecomment-550600422

Is there a way to handle this? I have to manually skipWaiting on browser in order to see changes/updates. Can't do the same on mobile.

**Comment by kikoanis** [comment]
If I understand you correctly, what you can do here is that in workbox.config file you can something like this and it will be added to the generated service-worker
```
self.addEventListener('message', (event) => {
    if (event.data.action === 'skipWaiting') {
        self.skipWaiting();
    }
});
```
Then in you just need to post a message ; something like
```registration.active.postMessage({ action: 'skipWaiting' });```

workbox.config is the file where you add your workbox strategies, routing...etc

**Comment by hanford** [comment]
Going to go ahead and close this, feel free to reopen if this problem still exists
