### ISSUE TITLE
Support static `/public` directory

### ISSUE THREAD

**Issue by dennispassway** [hanford/next-offline#203]
As of Next.js 9.1 the `/static` directory is deprecated and static files should be placed in the `/public` directory. [See blog release.](https://nextjs.org/blog/next-9-1#public-directory-support)

next-offline is still looking for the `manifest.json` in the `/static` directory.

It would be awesome if it also supported a `manifest.json` in the `/public` directory so we can get rid of the `/static` directory.

**Comment by hanford** [comment]
Would you be interested in making the change in a PR?

**Comment by hanford** [comment]
This should be fixed now, if anybody discovers anything please open a new issue

**Comment by dennispassway** [comment]
Sorry for not responding to your question, I missed the mesage. Thanks a lot for this fix!
