### ISSUE TITLE
Wrong precache manifest at 5.0.0-beta.9

### ISSUE THREAD

**Issue by robertu7** [hanford/next-offline#205]
## Issue
I updated to 5.0.0-beta.9 and run build next, the output `service-worker.js` contains files that in `build/public` (starting with `_next/public/`):

![image](https://user-images.githubusercontent.com/4065233/69053719-fef8e600-0a44-11ea-82da-b003d6a5d609.png)

Which will cause 404 in precache requests since Next.js doesn't handle `_next/public` .

## Expect
Only contains files that in `build/static` like `next-offline@4.x` does.

![image](https://user-images.githubusercontent.com/4065233/69053447-62364880-0a44-11ea-87d4-5beb1b244778.png)

**Comment by JipSterk** [comment]
what version of `next.js` do you have?

**Comment by robertu7** [comment]
@JipSterk Sorry, It's 9.1.2. 

My directory structure of static files is:

```
public
├── firebase-messaging-sw-develop.js
├── firebase-messaging-sw-production.js
├── robots.txt
└── static
    ├── apple-touch-icon.png
    ├── favicon-16x16.png
    ├── favicon-32x32.png
    ├── favicon-64x64.png
    ├── favicon.svg
    ├── icon-128x128.png 
    └── ...
```

**Comment by hanford** [comment]
@robertu7 can you try next-offline@5.0.0-beta.10 and report back?

**Comment by robertu7** [comment]
@hanford `5.0.0-beta.10` is working fine!
