### ISSUE TITLE
next-offline setup with nextjs 9

### ISSUE THREAD

**Issue by shih-js** [hanford/next-offline#206]
Hello world 👋🏼

I'm trying to convert an existing web app to a PWA, but for the life of me cannot get working. After spending hours googling around, I came across this post on spectrum `https://spectrum.chat/next-js/general/was-the-option-for-next-config-js-removed~1c53d740-e740-421b-bdd8-5a57f24bca23`

Can anyone confirm that they've remove support for next.config.js in 9+?

**Comment by hanford** [comment]
they aren't (or at least I don't think so??) @shih-js 

This app is on next 9.0.0 with a next.config.js https://github.com/hanford/personal-website

Going to go ahead and close this as it's not really an issue w/ next-offline
