### ISSUE TITLE
Use Next.js rewrites config

### ISSUE THREAD

**Issue by mfix22** [hanford/next-offline#211]
Hey @hanford what are your thoughts on using the new ["Custom Routing" `rewrites`](https://github.com/zeit/next.js/issues/9081) to add this rewrite:
```js
{
  "source": "^/service-worker.js$",
  "destination": "/_next/static/service-worker.js",
  "headers": {
    "Service-Worker-Allowed": "/"
  }
}
```
rewrite automatically?

**Comment by hanford** [comment]
Definitely not opposed!

Does this mean you wouldn't need to manually handle the service worker in your `now.json`?

**Comment by mfix22** [comment]
As far as I can tell from the rewrites proposal that shipped, yes!

**Comment by hanford** [comment]
@mfix22 would you be interested in a PR? I've been really busy lately 😅

**Comment by mfix22** [comment]
@hanford I'll try and get to it sometime, but I wouldn't assign me yet in case someone else can take it

**Comment by iamkevinwolf** [comment]
hey! i added PR #226 to solve this!

**Comment by mfix22** [comment]
@iamkevinwolf thank you! However, your PR does not solve the issue I am referring to, which is to let Next.js handle the rewrites, not Now.

In fact, I think I jumped the gun a little in posting this issue originally, since I think Next.js `rewrites` is still an experimental feature (AFAIK). 

@hanford if you want to close this issue, go ahead, and we can reconsider once rewrites becomes a default part of the Next.js API

**Comment by iamkevinwolf** [comment]
Oh ok got it. But I guess we can still use it as an updated example according to current Now2 API. 🤔

**Comment by cvolant** [comment]
Rewrites are not experimental anymore. It would be relevant to reopen this.
