### ISSUE TITLE
Now V2 functions

### ISSUE THREAD

**Issue by kennetpostigo** [hanford/next-offline#219]
Hey! I'm new to using nextjs and next-offline.

I'm curious about how `now.json` and `next.config.js` might change when using Now V2 functions. They are the new way of deploying lambdas that `now` is pushing. Do you know what changes we might have to make for `next-offline` configuration?

**Comment by oliverwebr** [comment]
Hi Kennet,

There is a small section in the read me, with a link to an example.
https://github.com/hanford/next-offline#now-20
