### ISSUE TITLE
Unnecessary `console.log`

### ISSUE THREAD

**Issue by unindented** [hanford/next-offline#22]
I think these [console statements](https://github.com/hanford/next-offline/blob/d89e87e384f02cf45e82177911894e19573fdd4c/register-sw.js#L4-L6) are unnecessary, given that Workbox is already pretty verbose. What do you think?

<img width="834" alt="screen shot 2018-04-21 at 5 30 57 pm" src="https://user-images.githubusercontent.com/69485/39090099-e905ce02-4589-11e8-9afd-a477bd2069fd.png">

**Comment by hanford** [comment]
I actually find it useful as my environment is typically `NODE_ENV=production` so workbox doesn't have any output.

What is probably a better solution though is making the additional logging an option that is disabled by default. I can probably get that out over the next few days, unless you want to take a crack at it.

cheers!
