### ISSUE TITLE
[Suggestion] Remove /\.map$/ from generated manifest file

### ISSUE THREAD

**Issue by Jarred-Sumner** [hanford/next-offline#236]
Currently, if you have sourcemaps, those will be precached by the service worker. Its not necessary, so it would be good to remove to reduce the number of requests the browser sends

Example:
![image](https://user-images.githubusercontent.com/709451/78514265-4fa77c00-7765-11ea-9d83-470c90ccd6c7.png)

**Comment by hanford** [comment]
Live in next-offline@5.0.1
