### ISSUE TITLE
Support custom dir + distDir

### ISSUE THREAD

**Issue by joaovieira** [hanford/next-offline#24]
From the discussion in #23:

> Handle exporting of Next apps that are on a custom `dir` (e.g. `/app` instead of `.`) and/or with a custom `distDir` (e.g. `/build` instead of `/.next`) as it's currently assuming everything will be built under `$projectRoot/.next`.

Don't know how to get this information in the `exportPathMap` step (https://github.com/hanford/next-offline/blob/master/export.js#L23) as I think this is only (?) exposed in the webpack config options. If there's any ideas/guidance I can do the PR.

**Comment by hanford** [comment]
@joaovieira we should be able to access this information from the `nextConfig` object if it's defined, otherwise we'd want to fallback to the default (`out` directory).

Let me know if you have any additional questions!
