### ISSUE TITLE
Ie11 arrow function issue

### ISSUE THREAD

**Issue by willcodes** [hanford/next-offline#25]
register-sw.js uses arrow functions which is not supported in ie11. I see there is an option to disable automatic registration to avoid this from being fired, but is there a way to customize this without injecting my own?

**Comment by hanford** [comment]
@willcodes we don't use the `this` context, so the arrow functions were just a style choice on my end.

I've migrated them to use the function keyword instead!

**Comment by hanford** [comment]
this fix is live in `next-offline@2.7.1`

**Comment by willcodes** [comment]
Hey thanks so much for the quick fix! By the way this library saved me a lot of time - awesome work
