### ISSUE TITLE
Please publish a new version with high vulnerabilities patched

### ISSUE THREAD

**Issue by dels07** [hanford/next-offline#265]
Hi,

Currently there's a commit from Sept 2020 regarding high vulnerabilities in `copy-webpack-plugin` & `serialize-javascript` which fixed in https://github.com/hanford/next-offline/commit/55501c4cde8a1b1bcadd0198556e7c3691079a45

However no newer release published to npm (last release 6 months ago), please at least publish a version with the patch applied.

Thanks

**Comment by hanford** [comment]
Just published `v5.0.3`

**Comment by dels07** [comment]
Btw you can also close https://github.com/hanford/next-offline/issues/218
