### ISSUE TITLE
Styles rendering

### ISSUE THREAD

**Issue by Huvik** [hanford/next-offline#27]
Hey, I was wondering if its possible with `styled-jsx` have styles rendered in the first load like server-side rendering does. Instead of "blink" between app without style and rendering it after the first render.

**Comment by hanford** [comment]
Hmm, things are working for me with the css-in-js library I've been using ([emotion](emotion.sh)) .. I can check `styled-jsx` some time tomorrow and let you know.

**Comment by hanford** [comment]
My personal website is here: [hanford/personal-website](https://github.com/hanford) if you want to check out the code

**Comment by hanford** [comment]
@Huvik not sure if the issue you're having is related to `next-offline` I've set up a small repo: [offline-styledjsx](https://github.com/hanford/offline-styledjsx) demonstrating that `styled-jsx` works entirely offline.

You can check out a live environment here: https://create-next-example-app-nqpmeicidf.now.sh/
