### ISSUE TITLE
Dev build fails if there is no .next dir

### ISSUE THREAD

**Issue by cyrilwanner** [hanford/next-offline#31]
Coming from cyrilwanner/next-compose-plugins#11, the development build/server fails when there is no `.next` directory containing a build. This can happen when a project is set up/cloned initially or when the folder gets removed before a new dev build.

I created a minimal repository to reproduce this bug with only next-offline used: https://github.com/cyrilwanner/next-offline-bug

I think that next.js always calls the function defined at `exportPathMap`, not only for production builds, in which next-offline tries to get the BUILD_ID file. If this is not needed for dev builds, we can probably add a check to skip this function if it is a dev build as you already do in the webpack config function.

**Comment by hanford** [comment]
In the middle of starting a new job. I'll hopefully get some time to dig a little deeper into this later this week, will update this issue accordingly

**Comment by hanford** [comment]
Thanks for opening the issue @cyrilwanner! haven't forgotten about this, just been very swamped.

**Comment by cyrilwanner** [comment]
No problem ;) Take your time, it's not a critical issue (at least for me) as next-offline can just be excluded in the development server phase when using next-compose-plugin. It's more of an improvement for people who don't use the compose plugin or when cloning a repository initially.
