### ISSUE TITLE
service-worker.js http 404

### ISSUE THREAD

**Issue by qihong1983** [hanford/next-offline#32]
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('/service-worker.js').then(function (registration) {
      console.log('SW registered: ', registration)
    }).catch(function (registrationError) {
      console.log('SW registration failed: ', registrationError)
    })
  })
}

**Comment by hanford** [comment]
?

**Comment by hanford** [comment]
I'm going to close until there is more information

**Comment by aduyng** [comment]
did you run `npm run build` before running `node server`?
