### ISSUE TITLE
Update next peer dependency

### ISSUE THREAD

**Issue by NathanielHill** [hanford/next-offline#33]
I believe `"next" :"^5.0.0 || ^6.0.0"` should do the trick.

**Comment by hanford** [comment]
I'm surprised `^5.0.0` doesn't encompass `6.0.0`.. 👀

**Comment by NathanielHill** [comment]
Yeah, that's only minor bumps:

https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers

You can always check with the calculator here:

https://semver.npmjs.com/

**Comment by hanford** [comment]
Thanks for sharing the calculator @NathanielHill, super useful resource

**Comment by NathanielHill** [comment]
No problem, I've used it a lot. In theory you could do something like `>=5`, but semantic versioning implies major releases have breaking changes which could make them incompatible with your package. So, seems best to simply add each new major version of next after verifying `next-offline` works :+1:
