### ISSUE TITLE
I need write a custom code in the service worker file

### ISSUE THREAD

**Issue by CharlyJazz** [hanford/next-offline#35]
I need write code to manage push notifications and more! How can i do it?

**Comment by hanford** [comment]
You'll need to pass in some `next-offline` specific options, and then some `workbox` options.

Things should looks something like this:

```js
withOffline({
  generateSw: false,
  swSrc: './path/to/my/sw.js'
})
```

by passing in `generateSw: false` next-offline utilizes the workbox injectManifest webpack loader. All options passed to next-offline automatically will be passed to that workbox loader.

Here is a link to their documentation: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#configuration

Let me know if you have any additional questions regarding `next-offline`!

**Comment by CharlyJazz** [comment]
Hi, Sr!

@hanford 

But if this is so because the generated service worker has these two lines:

![image](https://user-images.githubusercontent.com/12489333/43050502-a9f9ea90-8dd7-11e8-80b2-fb7ba1399437.png)

This is my configuration:

![image](https://user-images.githubusercontent.com/12489333/43050505-c290f378-8dd7-11e8-8cf0-fee0c6b85ae1.png)

Those two lines are in the generated sw. But I wrote in the configuration that the sw is not generated. In the same way, the sw has those two lines. And I do not need them.

Can you help me with any suggestion? Greetings.

This is my custom serviec-worker:

https://github.com/CharlyJazz/NextPWAFirebase/blob/master/worker/service-worker.js

My Next config file:

https://github.com/CharlyJazz/NextPWAFirebase/blob/master/next.config.js

**Comment by hanford** [comment]
I'll check out your repo when I get chance and dig a little deeper.

**Comment by CharlyJazz** [comment]
Cool @hanford Keep in touch!

**Comment by joaovieira** [comment]
@CharlyJazz 

```js
withOffline({
  generateSw: false,
  importWorkboxFrom: 'disabled', // don't include workbox again as you already have it
  swSrc: './path/to/my/sw.js'
})
```

Add to your hand-written (?) service worker:

```js
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});
```

**Comment by hanford** [comment]
Going to close this, looks like @joaovieira has adequately solved
