### ISSUE TITLE
Exclude _document.js

### ISSUE THREAD

**Issue by blazeu** [hanford/next-offline#36]
There is no `_document.js` in `_next` directory, but it is added to precache list, resulting 404 calls in SW.

**Comment by hanford** [comment]
Can you provide some additional information or a repo to reproduce this error? It's working for me in these two apps:

https://jackhanford.com/
https://trends.now.sh/

**Comment by blazeu** [comment]
Hmm, looks like it only happened in my dev machine and on my current project.

Building my current project in Netlify doesn't cause this problem.

Anyway, the error doesn't break the precaching, it's just a wasted network request.

Closing..

**Comment by hanford** [comment]
Interesting. Feel free to reopen if you can reliably repro.
