### ISSUE TITLE
Remove hard-coded assumptions

### ISSUE THREAD

**Issue by joaovieira** [hanford/next-offline#45]
If I wanted to output the generated service worker to any other place (e.g. `.next/static` or `static` - so they are automatically statically served) using `workboxOpts.swDest` then everything else breaks 😬

**Comment by hanford** [comment]
@joaovieira can I close in favor of this issue?

https://github.com/hanford/next-offline/issues/47

**Comment by joaovieira** [comment]
Yep 👍Will chime in there.
