### ISSUE TITLE
Support for Github Pages (gh-pages) prefix

### ISSUE THREAD

**Issue by danilobjr** [hanford/next-offline#46]
@hanford I'm trying to use `next export -o docs` to create a static site at `docs` folder and then deploy it to _gh-pages_.

A _Project Github Page_ as you know has the project name as a URL prefix: 

```
https://<user-name>.github.io/<project-name-as-prefix-here>
```

My case:

```
https://danilobjr.github.io/timer
```

**Problem**: The first line of the auto-generated _service-worker.js_ file has URLs pointed to `/_next/...`:

```
self.__precacheManifest = [{"url":"/_next/0b447979...
```

How can I achieve this?:

```
self.__precacheManifest = [{"url":"/timer/_next/0b447979...
```

Thanks in advance.

**Comment by joaovieira** [comment]
@danilobjr for Next-generated files, setting the Next.js's top-level [`assetPrefix` option](https://github.com/zeit/next.js/#cdn-support-with-asset-prefix) should do it. For your own files, check the `modifyUrlPrefix` for `workboxOpts`: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_generatesw_config

**Comment by hanford** [comment]
@danilobjr can you try what @joaovieira suggested and report back? Going to close the issue in the meantime. 

Happy to reopen if we need to further investigate

**Comment by joaovieira** [comment]
Ah, for that I'm registering the SW myself in `_document`:

```jsx
          {/* Register Service Worker */}
          <script
            nonce={nonce}
            dangerouslySetInnerHTML={{
              __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function () {
                  navigator.serviceWorker.register('${appPath('/service-worker.js')}', {
                    scope: '${appPath('/')}',
                  }).then(registration => {
                    console.log('ServiceWorker registration successful with scope: ', registration.scope);
                  }).catch(err => {
                    console.error(err);
                  });
                });
              }
              `,
            }}
          />
```

You can get the asset prefix from `this.props.__NEXT_DATA__.assetPrefix`.

**Comment by danilobjr** [comment]
@joaovieira `scope` made it happen! :smiley: 

Thank you guys.
