### ISSUE TITLE
Build `service-worker.js` to `/static` to work better with `next export`

### ISSUE THREAD

**Issue by mfix22** [hanford/next-offline#47]
Since `next export` automatically copies files from `/static` into the build folder, if the `service-worker.js` was output to there, then users wouldn't have to manually copy it over to the public directory (like we do [here](https://github.com/dawnlabs/carbon/blob/master/Dockerfile))

**Comment by hanford** [comment]
Would love a PR

Feel free to ping me if you have any questions!

**Comment by joaovieira** [comment]
The sw output should be defined by the `swDest` option from workbox and everything else should work around it. 

Is `/static` the right place? That's what `next-workbox` does, but it felt odd to me as well given it's not a generated folder and generating files into user folders may be unexpected. On the other side, `.next/static` is not automatically exported.

Ideas?

**Comment by mfix22** [comment]
It was actually working correctly! There was just a bug from using path.join instead of resolve (: PR mentioned above fixes it
