### ISSUE TITLE
Use workbox precache manifest output

### ISSUE THREAD

**Issue by joaovieira** [hanford/next-offline#49]
While digging in I found out that `workbox-webpack-plugin` limits all of the "transform" options to the `globPattern` files only. I.e. don't run `modifyUrlPrefix` on webpack-generated assets, for example. See whole explanation [here](https://github.com/GoogleChrome/workbox/issues/1591#issuecomment-415727436).

I then found out this will be available in `workbox-webpack-plugin` v4: https://github.com/GoogleChrome/workbox/issues/1591

We can still do all of that work manually:

1. Read contents of `precache-manifest.*.js`
2. Mimic `modifyUrlPrefix` according to the existing `exportPathMap`
3. Remove revision from hashed files (maybe all)
4. Ignore unserved files (e.g. `build-manifest.json`)

I'd be ok to wait for v4, given the current version is working fine. Reading from the generated precache manifest is just a more accurate process.

**Comment by hanford** [comment]
Sounds good to me!

**Comment by hanford** [comment]
Good catch! I can probably fix that today or this weekend unless you can beat me to it

**Comment by joaovieira** [comment]
Nope, go ahead. I'll be on hols for the next week 😄
