### ISSUE TITLE
How to transpile autogenerated service worker

### ISSUE THREAD

**Issue by Beelphegor** [hanford/next-offline#50]
Hi, 

My autogenerated service worker has a trailing comma when using the importScripts option from workbox, this is causing the service worker to fail to register in browsers that do not support the trailing comma on methods like Edge. Is there a way to transpile the autogenerated file before copying to ./next folder?

My config
```javascript
 [
      withOffline,
      {
        workboxOpts: {
          globPatterns: ['static/**/*'],
          globDirectory: '.',
          runtimeCaching: [
            { urlPattern: /^https?.*/, handler: 'networkFirst' }
          ],
          importScripts: [
            'https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-precaching.prod.js'
          ]
        }
      }
    ]
```

Autogenerated trailing comma
```javascript
importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-sw.js");

importScripts(
  "https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-precaching.prod.js",
  
);
```

Thanks : )

**Comment by joaovieira** [comment]
@Beelphegor I've opened a PR to fix that. Meanwhile, you don't need to load that `workbox-precaching` module as it's automatically included in the first (https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_workbox_sw_via_cdn).

**Comment by joaovieira** [comment]
Also, your `static` files are cached by default now - see https://github.com/hanford/next-offline/pull/44. So you don't need any custom `workboxOpts` anymore 🎉
