### ISSUE TITLE
Cannot register service-worker

### ISSUE THREAD

**Issue by DastanSE** [hanford/next-offline#56]
We have recently moved our application to Next.js and are now having difficulties loading the service worker. 
We were able to register the service worker using a simple example. However, as soon we started to add more pages and loading data from the server. We are not sure how to configure correctly next-offline workbox options. The service worker gives us the error; 
```
ERROR: SW registration failed: TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```
Does anyone know which configurations or files we should be looking to fix this?  A working example with caching fetching data from the server would also be great. Thank you!

**Comment by hanford** [comment]
@DastanSE are you using `next export`? next-offline should work out of the box.

My [personal website](https://github.com/hanford/personal-website) and this [side project](https://github.com/hanford/trends) both use next-offline and it works on/offline.

**Comment by DastanSE** [comment]
Thanks for the reply. I was able to register service-worker. But had a new issue my website start to reload infinite time. This is my server.js code. 
```
const { createServer } = require('http')
const { join } = require('path')
const { parse } = require('url')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 4040
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const routes = require('./routes');

const nextHandler = app.getRequestHandler();
const handle = routes.getRequestHandler(app);

app.prepare()
  .then(() => {
    createServer((req, res) => {
      const parsedUrl = parse(req.url, true)
      const { pathname } = parsedUrl;
      const nextPaths = [
        '/_next/',
        '/_webpack/',
        '/__webpack_hmr',
        '/static/'
      ];

      if (nextPaths.some(path => req.url.startsWith(path))) {
        nextHandler(req, res) 
      } else if (pathname === '/service-worker.js') {
        const filePath = join(__dirname, '.next', pathname)
        app.serveStatic(req, res, filePath)
      } else {
        handle(req, res, parsedUrl)
      }

    })
      .listen(port, (err) => {
        if (err) throw err
        console.log(`> Ready on http://localhost:${port}`)
      })
  })
```

if I remove 
```if (pathname === '/service-worker.js') {
        const filePath = join(__dirname, '.next', pathname)
        app.serveStatic(req, res, filePath)``` this part of code site stop reloading but cant register service worker. I think maybe my server.js is wrong. 

I'm using next-routes; that's why handler comes from routes;

**Comment by hanford** [comment]
Going to close for now. If you provide more info we can look deeper!

**Comment by heshamelmasry77** [comment]
please reopen the issue i have the same problem it is not solved

**Comment by hanford** [comment]
@heshamelmasry77 feel free to open a new issue, please provide steps to reproduce your error and information about which next/next-offline version you're using
