### ISSUE TITLE
Quota exceeded errors and purgeOnQuotaError

### ISSUE THREAD

**Issue by gugiserman** [hanford/next-offline#57]
We're currently using `next-offline` for a very basic offline support with all default settings, but recently we have noticed a lot of "Quota Exceeded" errors in production.

I was taking a look at the `workbox` documentation and found this:
- https://developers.google.com/web/tools/workbox/guides/storage-quota

So, is there a way to set the value of `purgeOnQuotaError` on the expiration plugin? I couldn't find a way to pass this option or the expiration plugin itself.

**Comment by hanford** [comment]
Looks like `next-offline@2.12.0` was using `workbox@3.2.0` which was an older version, So I've just updated and published `next-offline@2.13.0` which ships with `workbox@3.5.0` so first ensure that you're on the newest version of `next-offline`

Finally it looks like you'd want your workboxOpts to look something like this:

```js
withOffline({
  workboxOpts: {
    runtimeCaching: [
      {
        urlPattern: /api/,
        handler: 'networkFirst',
        options: {
          expiration: {
            // Keep at most 50 entries.
            maxEntries: 50,
            // Don't keep any entries for more than 30 days.
            maxAgeSeconds: 30 * 24 * 60 * 60,
            // Automatically cleanup if quota is exceeded.
            purgeOnQuotaError: true,
          },
        }
      }
    ]
  }
})
```

**Comment by gugiserman** [comment]
Hey, @hanford 

This is happening:
- https://github.com/GoogleChrome/workbox/issues/1642

**Comment by hanford** [comment]
@gugiserman I've subscribed too

**Comment by joaovieira** [comment]
Given I updated all the packages in #59, that included `workbox@3.6.1` with the fix for this (https://github.com/GoogleChrome/workbox/releases/tag/v3.6.1). That's only for next 7 though. Do you want to cut a hot fix patch for the 2.x release?

**Comment by hanford** [comment]
@joaovieira I'm pretty sure ^ just results in some console.error messages. I think we could probably just ask that users upgrade their next project and subsequently next-offline given there wasn't many breaking changes.

I don't feel too strongly either way. If someone asks for a 2.x patch I'd be okay doing it.

**Comment by hanford** [comment]
@gugiserman have you upgraded to next 7 yet?

**Comment by gugiserman** [comment]
@hanford Not yet, we're still on next 6 😞 We are upgrading sooner than later, but since we have more than one product running on nextjs, we will probably deal with nextjs 6 for a little longer.

**Comment by hanford** [comment]
Just published a new version of 2.X with `workbox@3.6.1` so @gugiserman if you update to `2.13.2` and let me know if this issue is resolved, we can go ahead and close this!

**Comment by hanford** [comment]
going to close, comment if it happens again and we can continue investigating
