### ISSUE TITLE
Great Plugin

### ISSUE THREAD

**Issue by designspin** [hanford/next-offline#6]
Hi,

I was using the sw-precache-webpack plugin to get offline support working. I had this setup alongside Onesignal for push notifications. The thing is I have to import my service worker with importScripts into the Onesignal workers.

Is there any way of disabling the registration of the service worker provided by this plugin, so I can just import it or manually start it myself?

**Comment by designspin** [comment]
Okay, I managed to get it working by using the further webpack configuration function provided:

entries['main.js'] = entries['main.js'].filter(entry => !entry.endsWith('next-offline/register-sw.js'));

I have a custom server setup, I have a route setup for articles, so urls like /article/:slug

For these routes I get a 404 from the service worker, how can I overcome this?

**Comment by hanford** [comment]
@designspin I can easily add an option to disabling `next-offline` from automatically registering. I'll try and get to it sometime early next week and will update this thread accordingly

**Comment by designspin** [comment]
@hanford , I got around it easy enough, but I guess that would be useful as part of your plugin for future users. I'll update to latest version when available. Thanks for the plugin, a lot tidier than what I had going prior to discovering this.

**Comment by hanford** [comment]
@designspin added a top level `dontAutoRegisterSw` flag which is live in version `2.1.0` it should allow you to easily disable the behavior you mentioned above.

Let me know if you have any other ideas!
