### ISSUE TITLE
Generating empty importScripts()

### ISSUE THREAD

**Issue by db-dblank** [hanford/next-offline#60]
My `next-offline` options:
```javascript
{
  dontAutoRegisterSw: true,
  generateSw: false,
  workboxOpts: {
    swSrc: "./server/sw.js",
    swDest: "service-worker.js",
  },
}
```
\
Original `importScripts()` generated by `workbox-webpack-plugin`:
```
importScripts("precache-manifest.80484f727fa927a948f274db14a17584.js", https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-sw.js");
```
\
Final `importScripts()` generated by `next-offline` on version **`2.11.0`:**
```
importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-sw.js");
```
\
Final `importScripts()` generated by `next-offline` on version **`2.12.0` and above**:
```
importScripts();
```
\
I believe that the problem started with https://github.com/hanford/next-offline/commit/8399e41d74a1ba23537079e4979decc31104891c

**Comment by hanford** [comment]
Hmm @db-dblank I'll probably have some time in the next week to take a look. Will update this thread!

**Comment by joaovieira** [comment]
Yeah, weird behaviour. But I got it - there's a bug in the new regex.

**Comment by hanford** [comment]
@joaovieira no worries, I'm hoping to take a look this coming Monday as it's a holiday in the US. 

While it's not ideal, AFAIK it's not breaking anything.

**Comment by hanford** [comment]
Didn't have any time yesterday to look, will hopefully get some time this week. 

If anyone is a regex champ, feel free to jump in! 🙇‍♂️

**Comment by orditeck** [comment]
Is there a temporary fix for this? Like something to set in the configs?

**Comment by orditeck** [comment]
Opened a PR #66

**Comment by orditeck** [comment]
So... the `importScripts` seems fixed, however, `precache-manifest.6c432c5028d94e1e1925117ba156149a.js` doesn't exist. For example, when doing `next build && next export`, there's no `precache-manifest.*.js` file in the `out` directory. 

Am I missing something?

**Comment by joaovieira** [comment]
We don't want to copy the generated manifest. It has wrong paths. We build a new one based on that and replace it with an inline version in the final SW. So, if you see a precache-manifest in your final SW, that's wrong :) 

Your issue may be a separate thing. What is your next config?
