### ISSUE TITLE
Upgrade to Workbox v4

### ISSUE THREAD

**Issue by hanford** [hanford/next-offline#62]
Workbox 4.0 just came out which is exciting. I'd love to upgrade `next-offline` once stable drops.

https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-alpha.0

**Comment by joaovieira** [comment]
Just tried it to see if they normalized their `importScripts` between generating and injecting. Still the same, but the good news is that v4 just works.

**Comment by hanford** [comment]
Yep ;) I tried it out too!

Wonder when they plan on releasing it.. Was thinking maybe at/around this event https://developer.chrome.com/devsummit/

**Comment by hanford** [comment]
looks like the alpha has been tweaked a little bit and is now in beta!

https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-beta.0

**Comment by hanford** [comment]
Workbox 4 RC.0 was released yesterday!

https://twitter.com/workboxjs/status/1093316874933161984

**Comment by samanmohamadi** [comment]
Workbox 4 was released yesterday.

**Comment by hanford** [comment]
@samanmohamadi yep! I'm hoping I'll get some time to make the transition either this weekend or next.

Should close several issues in this plugin
