### ISSUE TITLE
This vs.  workbox-webpack-plugin (question)

### ISSUE THREAD

**Issue by jasan-s** [hanford/next-offline#63]
This is a question, not an issue. I am unclear as to why I would use this lib instead of `workbox-webpack-plugin` which this seems to also use.  Is it an abstraction layer over it .

**Comment by hanford** [comment]
it is @jasan-s, this plugin easily integrates with how the Next.js team recommends people compose their next.config's

you can see some examples [here](https://github.com/hanford/personal-website/blob/master/next.config.js) and [here](https://github.com/hanford/trends/blob/master/next.config.js)

Feel free to reopen or create a new issue with any questions you might have!
