### ISSUE TITLE
Configure Next Bundle Analyzer Plugin

### ISSUE THREAD

**Issue by 1nullpointer** [hanford/next-offline#65]
Am trying to setup [Next Bundle Analyzer Plugin](https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer)

Still trying to get it working, 
can you please help confirm if this is the right way to add it in next.config.js
Thanks

How do we actually add multiple configs .Say, I want to add [next-css plugin](https://github.com/zeit/next-plugins/tree/master/packages/next-css)
module.exports = withCSS()

```
const withOffline = require('next-offline')
//const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const withBundleAnalyzer = require("@zeit/next-bundle-analyzer");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");

module.exports = withOffline({
  distDir: "../../dist/functions/next",
  webpack:withBundleAnalyzer({
    analyzeServer: ["server", "both"].includes(process.env.BUNDLE_ANALYZE),
    analyzeBrowser: ["browser", "both"].includes(process.env.BUNDLE_ANALYZE),
    bundleAnalyzerConfig: {
      server: {
        analyzerMode: 'static',
        reportFilename: '../../bundles/server.html'
      },
      browser: {
        analyzerMode: 'static',
        reportFilename: '../bundles/client.html'
      }
    }
  })
})
```

**Comment by hanford** [comment]
@1nullpointer so the way most of these plugins should work is by extending the the `next.config` object.

so in the above case it something like this would work

```js
const config = {
  webpack: {
    ..
  },
  distDir: '..'
}

const hasOffline = withOffline(config)
// notice here we're passing the composed object into withCSS
const hasCSS = withCSS(hasOffline)
// notice here we're passing the composed object into withBundleAnalyzer
const hasBundleAnalyze = withBundleAnalyzer(hasCSS)

module.exports = hasBundleAnalyze

```

Basically, each zeit plugin should take an object, extend it with its own functionality and returned the extended object allowing other plugins to do the same.

If you look at how `next-offline` works, you can see we simply take [the config object](https://github.com/hanford/next-offline/blob/master/index.js#L9) we decorate it adding in our own code, and then [return the extended object](https://github.com/hanford/next-offline/blob/master/index.js#L63)
