### ISSUE TITLE
Doesn't work with next-manifest

### ISSUE THREAD

**Issue by orditeck** [hanford/next-offline#67]
I don't know why, but using [next-manifest](https://github.com/ragingwind/next-manifest) with next-offline causes the latter to break. It doesn't register the worker anymore.

See https://github.com/ragingwind/next-manifest/issues/5

Anyone has an idea why those two are incompatible? I'd like to help.

**Comment by hanford** [comment]
@orditeck can you share your next config?

**Comment by orditeck** [comment]
```js
const withPlugins = require('next-compose-plugins');
const sass = require('@zeit/next-sass');
const offline = require('next-offline');
const manifest = require('next-manifest');

module.exports = withPlugins(
    [sass, offline, [manifest, {
        manifest: {
            "name": "Nevek.co",
            "short_name": "nevek.co",
            "start_url": "/",
            "display": "standalone",
            "background_color": "#FFE066",
            "theme_color": "#FFE066",
            icons: false
        }
    }]
    ], {
        distDir: 'build'
    });
```

You may clone [from this commit](https://github.com/orditeck/nevek.co/tree/c26e5d5c950fcd1048f9d4e213ab4e9382d652c7) if you want to test.

For now I removed `next-manifest`.

**Comment by hanford** [comment]
Ahhh. could you actually try removing `next-compose-plugins`? That's broken some things in the past.


Can you let me know what happens when your next.config looks like this:

```js

const withSass = require('@zeit/next-sass');
const withOffline = require('next-offline)
const withManfiest = require('next-manifest)

const config = {
  distDir: 'build'
}

const hasSass = withSass(config)
const hasManifest = withManifest(hasSass, {
  manifest: {
    "name": "Nevek.co",
    "short_name": "nevek.co",
    "start_url": "/",
    "display": "standalone",
    "background_color": "#FFE066",
    "theme_color": "#FFE066",
    icons: false
  }
})

const hasOffline = withOffline(hasManifest)

module.exports = hasOffline
```

**Comment by orditeck** [comment]
Will do tomorrow's evening. Will let you know, thanks!

**Comment by hanford** [comment]
Keep me posted!

**Comment by hanford** [comment]
@orditeck I confirmed removing next-compose-plugins does indeed fix the issue.

You can check out this repo here which should be working as intended:

https://github.com/hanford/next-offline-issue-67

I'll hopefully have some time this weekend to investigate next-compose-plugins and can probably find a fix, though for now I'd suggest removing it.

**Comment by hanford** [comment]
@Enalmada are you using next-compose-plugins?

**Comment by Enalmada** [comment]
Not intentionally that I am aware of...

**Comment by hanford** [comment]
ah, interesting. 

Could you share your `next.config`?

**Comment by Enalmada** [comment]
Sure, I will clean it up and post in a bit.

**Comment by Enalmada** [comment]
@hanford Here is the next.config from my sample project: https://github.com/Enalmada/next-reason-boilerplate/blob/master/next.config.js

@joaovieira Take a look at how I am using "phase".  You might get slightly better performance if you don't load things in production you don't need.  I have no idea what the real impact is though.

**Comment by hanford** [comment]
we can continue this conversation in #69
