### ISSUE TITLE
precache-manifest not copied on next export

### ISSUE THREAD

**Issue by orditeck** [hanford/next-offline#68]
```js
next build

Created:
/${distDir}/service-worker.js
/${distDir}/precache-manifest.${hash}.js
```

```js
next export

Created:
/out/service-worker.js

Missing:
/out/precache-manifest.${hash}.js
```

Resulting in

```console
A bad HTTP response code (404) was received when fetching the script.
SW registration failed:  TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

**Comment by hanford** [comment]
@orditeck we actually don't want to bring over the precache-manifest, we should be inlining everything into the service worker file. 

When I run export on my [personal website](https://github.com/hanford/personal-website), it seems to be working.. (though I'm not using your most recent PR with the fix for the empty importScripts)

**Comment by hanford** [comment]
from my website, this is the sw that is generated: https://gist.github.com/hanford/820889bd088a383bedff317b82f17f46

**Comment by orditeck** [comment]
In https://gist.github.com/hanford/820889bd088a383bedff317b82f17f46,
```
importScripts(
  
);
```

should not be empty (which is fixed by #66), it should be something like [this](https://github.com/orditeck/nevek.co/blob/727f701fe82cdb1a816b0ceec28ae8b19f4699e5/service-worker.js#L47).

Which would result to the same issue I have. So we should either not import the precache-manifest script or remove the inlined manifest.

**Comment by joaovieira** [comment]
Sorry, I commented on the original thread: https://github.com/hanford/next-offline/issues/60#issuecomment-434828968

**Comment by joaovieira** [comment]
Does the generated SW start with `self.__precacheManifest = ...`?

**Comment by orditeck** [comment]
@joaovieira I already linked my generated SW in my previous post above if you wan't to take a look.

**Comment by joaovieira** [comment]
Sorry, my bad. Yeah, that looks like a good SW.

**Comment by orditeck** [comment]
I'll test that v3.0.4 fix this in the next minutes.

**Comment by hanford** [comment]
Thanks, let me know and I'll close if its fixed

**Comment by orditeck** [comment]
It still produces an empty `importScripts();` which should ideally be removed when empty but it works.
