### ISSUE TITLE
Workbox configuration options that are not needed?

### ISSUE THREAD

**Issue by 4cm4k1** [hanford/next-offline#72]
Hi! 👋

Thank you for this great package. I'm seeing this output and just wondering if there's anything to be concerned about (or would become a concern in the future):

```shell
WARNING You're using the following Workbox configuration options: [globDirectory, globPatterns]. In Workbox v3 and later, this is usually not needed. Please see https://goo.gl/EQ4Rhm for more info.
```

Thanks!

**Comment by hanford** [comment]
What are you using those for @4cm4k1?

We're following semver so the next breaking change will be a major version bump in this repo / on npm v(3 -> 4) .. and most package managers won't grab the new version unless you manually install the @latest version.

**Comment by hanford** [comment]
@4cm4k1 ahh, just noticed we are adding those on our sides. I'll make sure to remove them either sometime this week or next!

**Comment by 4cm4k1** [comment]
Ah, great! Your first reply had me confused, and so I was trying to investigate if/how I was grabbing a different `workbox` version. Thanks for maintaining this package! Can't wait to see the improvements in v4, also!

**Comment by hanford** [comment]
@joaovieira I think you added [these defaults](https://github.com/hanford/next-offline/blob/master/index.js#L25)

They should be safe to remove, right?
