### ISSUE TITLE
Please, provide a basic next.js + next-offline + express custom server basic example

### ISSUE THREAD

**Issue by realtebo** [hanford/next-offline#75]
I'm starting from scratch and actually I have 

```
/static/favicon.ico
/static/pages/index.js
/static/pages/about.js
/server.js
/next.config.js
```

/server.js
-

```
const express = require('express')
const next = require('next')
const path = require('path')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare()
  .then(() => {
    const server = express()

    server.get("/service-worker.js", (req, res) => {
      // Don't cache service worker is a best practice (otherwise clients wont get emergency bug fix)
      res.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
      res.set("Content-Type", "application/javascript");
      if (dev) {
        console.log('dev - sw from static');
        app.serveStatic(req, res, path.resolve("./static/service-worker.js"));
      } else {
        console.log('next - sw from next');
        app.serveStatic(req, res, path.resolve("./.next/service-worker.js"));
      }
    });

    server.get('*', (req, res) => {
      return handle(req, res)
    })

    server.listen(3000, (err) => {
      if (err) throw err
      console.log('> Ready on http://localhost:3000')
    })
  })
  .catch((ex) => {
    console.error(ex.stack)
    process.exit(1)
  })

```

/next.config.js
-

```
const withOffline = require('next-offline')

module.exports = withOffline();
```

/pages/index.js
-

```
import Link from 'next/link'
import Head from 'next/head'

const Index = () => (
  <div>
    <Head>
      <title>My page title</title>
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link rel="icon" href="/static/favicon.ico"></link>
    </Head>

    <Link href="/about">
      <a>About Page</a>
    </Link>
    <p>Hello Next.js</p>
  </div>
)

export default Index
```

/pages/about.js
-

```
export default () => (
  <div>
    <p>This is the about page</p>
  </div>
)

```

scripts in package.json
-

```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node server.js",
    "build": "next build",
    "export": "next export",
    "start": "cross-env NODE_ENV=production node server.js"
  },
```

After `npm run build`, I execute `npm start`.

Is this the right way to combine next, espress and next-offline?

What make me suspecting that something is wrong is that in production (`npm start`) , if I go online, visist index and about, then go offline, all is working _until I reload the page when am I offline_: in this case the /static/favicon.ico is not served. It gives a 404. 

In the readme I see

> By default next-offline will precache all the Next.js webpack emitted files and the user-defined static ones (inside /static) - essentially everything that is exported as well.

So I was expecting the /static/favicon.ico must be automatically included in app cache. Also, as you can see, to (uselessly try to) force the cachine of favicon.ico, I added manually the head meta link to point to /static/favicon.ico.

What am I doing wrong? What's the right way to write the server.js? Must manually setup a route to distinguish dev and production mode for service-worker.js? 

Thanks in advance

**Comment by hanford** [comment]
I'm not sure I understand exactly what isn't working for you. I have two project using Next.js + next-offline + express that might help.

my personal website which is [here](https://jackhanford.com) and the code is [here](https://github.com/hanford/personal-website)

And trends, which the application is [here](https://trends.now.sh) and the you can see the code [here](https://github.com/hanford/trends)

Both applications work offline, and you can see they're built in a similar way where they simply serve the service worker when the request comes in 

```js
const app = next({ dir: '.', dev });

app.prepare().then(() => {
  ...

  server.get('/service-worker.js', ServiceWorker(app));

  server.get('*', (req, res) => {
    return handle(req, res);
  });
});

const ServiceWorker = app => (req, res) => {
  const filePath = join(__dirname, '../', '.next', 'service-worker.js');

  app.serveStatic(req, res, filePath);
};

```

**Comment by realtebo** [comment]
I tought it could be a problem in my config because when offline i cannot see the favicon; actually, seems it's a weel-know behaviour of chromium, and the problem will be limited to only the favicon;; so I'll go on ignoring the favicon offline.

I ask kindly a basic example of integration with express, and 2 lines of documentation to cover the common questions:

- [ ] how to pass options to workbox?
- [ ] i'd like to see the sw in action when running `npm run dev`, so how to enable _autogeneration_ of service-worker.js_ in development?
- [ ] how to _add code_ to service-worker.js_ without disabling the automatically generated one?
- [ ] how to enable set debug to off when running  `npm start` on localhost?

Thanks for your plugin!

**Comment by gauravdhiman** [comment]
To see service worker in action with automatic generation of `service-worker.js` on your localhost, do below things:
1. Configure your NextJS server to run in prod mode.
`const app = next({ dir: '.', dev: false });`

2. Build your NextJS app by running `npm run build`. In case your client code not in your app's top folder, then give name of client folder at the end of build command. Lets say the client / nextjs code is in `client` folder, then build using `npm run build client`.

3. Start the server `npm run start`

-----

Another way is to let the server run in `dev` mode, but in custom server check if the request if for `/service-worker.js` and app is in dev mode (`process.env.NODE_ENV !== 'production';`) then serve your manually scripted `service-worker.js`, that you can place in `/static` or in any other folder of your app.

**Comment by hanford** [comment]
@realtebo you can also take a look at how the tests work (we have a sample next.js application that we test against)

https://github.com/hanford/next-offline/tree/master/tests

Though you'll likely not want to include this part: https://github.com/hanford/next-offline/blob/master/tests/next.config.js#L28

Because we do have some code you can go off of, I'm going to close this issue. Feel free to open another if you have additional questions or issues

**Comment by Quadriphobs1** [comment]
it doesnt look like it got registered with the express setup and @hanford  the examples you referenced are not express setup not even custom server setup

**Comment by patsadow2** [comment]
I am also wondering how to adjust it, i don't want to use NOW.JS

**Comment by hanford** [comment]
@Quadriphobs1 ahhh, I migrated off of that stack onto serverless whenever Zeit introduced that.

@Quadriphobs1 @patsadow2 this old version of my personal website may be helpful:
https://github.com/hanford/personal-website/tree/1526bce2d57c9027136b5b4fe262b0dd5bbdafc5

**Comment by Quadriphobs1** [comment]
Yeah I was able to get it work, I realised the folder pointed to is wrong as my express file is located inside `/dist/server/`
