### ISSUE TITLE
How can unregister service worker?

### ISSUE THREAD

**Issue by xcv58** [hanford/next-offline#81]
It seems the old service worker will be always there if we just remove the plugin for next.config.js.

Is there any instruction to unregister the existing service worker? Thanks.

**Comment by hanford** [comment]
Not certain I understand what the issue you’re having is.

You can unregister a service worker using the service worker API: https://stackoverflow.com/questions/33704791/how-do-i-uninstall-a-service-worker

But I don’t manually do this in any of my projects. How come you need to unregister?

**Comment by xcv58** [comment]
Thanks, @hanford it's for this issue: https://github.com/hanford/next-offline/issues/77

Let me create a reproduce repo for broken video on iOS devices.

**Comment by xcv58** [comment]
Here is the reproduce repo: https://github.com/xcv58/next-offline-issue-77

To make the video work on iOS devices, it requires either adding `workbox-range-request` plugin or remove the service worker completely.

Also even without the video issue. Simply remove the offline plugin will lead to undesired behavior if someone already has the servicer worker installed. 

Create react app provide a simple way to safely unregister service worker: https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app#offline-first-considerations

I think we should follow the same logic for servicer worker support.

**Comment by hanford** [comment]
>Create react app provide a simple way to safely unregister service worker: facebook.github.io/create-react-app/docs/making-a-progressive-web-app#offline-first-considerations

>I think we should follow the same logic for servicer worker support.

Good idea! Check out the PR #82 I've added the ability to control registration / unregistering in your own application. I'll probably merge it sometime tomorrow.

-- 

I'll look at the video when I get some more time.

**Comment by xcv58** [comment]
Great, thank you @hanford

**Comment by hanford** [comment]
@xcv58 runtime control is live in version `v3.2.0`!

**Comment by danny-wang** [comment]
as for me , i just use a new  nonexistent scope service worker to replace old one,

 ServiceWorker: {
        events: true,
        // what range of URLs a service worker can control. Use a nonexistent path to disable ServiceWorker
        scope: '/disable-service-worker/',
      },

as for the app.js, i add below code to unregister old sw:

if ('serviceWorker' in navigator) {
  navigator.serviceWorker.getRegistrations().then(registrations => {
    for (const registration of registrations) {
      // keep only serviceWorker which scope is /disable-service-worker/, The purpose is to make serviceWorker useless
      if (registration.scope.includes('/disable-service-worker/') === false) {
        registration.unregister()
      }
    }
  });
  // clear cache of service worker
  caches.keys().then(keyList => {
    return Promise.all(
      keyList.map(key => {
        return caches.delete(key);
      }),
    );
  });
}
