### ISSUE TITLE
404 servce-worker.js http 404

### ISSUE THREAD

**Issue by qihong1983** [hanford/next-offline#83]
Request URL: http://localhost:3000/service-worker.js
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Referer: http://localhost:3000/service-worker.js
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

404 pages

next-config.js

const withOffline = require('next-offline')

// module.exports = withOffline({ dontAutoRegisterSw: true })
module.exports = withOffline({
  webpack(config, options) {
    return config
  }
})

?????

**Comment by hanford** [comment]
can you please help me reproduce the error?

Do you have a custom server that is serving the service worker? You can see what it should look like here: https://github.com/hanford/next-offline#usage

Here are some example projects that are successfully using next-offline:

my website: https://github.com/hanford/personal-website
side project: https://github.com/hanford/trends

**Comment by qihong1983** [comment]
cool 
think you 
i like this
