### ISSUE TITLE
[issue] Improper url generated in precache manifest 

### ISSUE THREAD

**Issue by rtm619** [hanford/next-offline#84]
Hi, 

I am using Next-Offline plugin with default configuration to generate a SW in my next app. I am using it with next-compose-plugins. But some of the urls in the precache manifest is coming up in a wrong format. 

```
[
  {
    "url": "/_next/static\\KNDFTKSOllSWsMpFn4rTQ\\pages\\articles\\article-tw-styles.js"
  },
  {
    "url": "/_next/static/chunks/commons.86fc779777898d71ec9d.js"
  },
  {
    "url": "/_next/static/runtime/main-41ce168f4e04b48f4931.js"
  },
  {
    "url": "/_next/static\\KNDFTKSOllSWsMpFn4rTQ\\pages\\_app.js"
  },
  {
    "url": "/_next/static\\KNDFTKSOllSWsMpFn4rTQ\\pages\\_error.js"
  },
  {
    "url": "/_next/static\\KNDFTKSOllSWsMpFn4rTQ\\pages\\articles\\article-detail.js"
  },
  {
    "url": "/_next/static\\KNDFTKSOllSWsMpFn4rTQ\\pages\\articles\\article-list.js"
  },
  {
    "url": "/_next/static/runtime/webpack-89179faa512dd01fbb62.js"
  },
  {
    "url": "/_next/static\\KNDFTKSOllSWsMpFn4rTQ\\pages\\homePage.js"
  },
  {
    "url": "/_next/static/css/styles.1922a2a1.chunk.css"
  },
  {
    "url": "/_next/static/chunks/styles.afe210c5d5c033637b26.js"
  },
  {
    "url": "/_next/static/images/Braun-Garantieverlaengerung-Landing-2a7a96eccf353053883657a0102e1411.jpg"
  },
  {
    "url": "/_next/static/images/loader-9e0373c2b4410c49439dfd822c5fd16e.gif"
  }
];
```
As you can see, the files inside the buildId folders are the only ones that are affected. 
I feel like this is something related to the path module.

Any idea why its happening?

My config: 

Platform: Windows 10 
Next: 7.0.2
Next-Offline: 3.1.0

**Comment by hanford** [comment]
@rtm619 on holiday right now, should be able to take a look sometime early-ish this coming week

**Comment by Huaoe** [comment]
see my pull request to as fix https://github.com/hanford/next-offline/pull/91

**Comment by Huaoe** [comment]
// next.config.js
const fetch = require('isomorphic-unfetch')
const withPlugins = require('next-compose-plugins');

const withOffline = require('next-offline')

const optimizedImages = require('next-optimized-images')

const { ANALYZE } = process.env

module.exports = withPlugins(
    [
        [optimizedImages, {
            /* config for next-optimized-images */
        }],

        [withOffline, {
            dontAutoRegisterSw: true,
            workboxOpts:{
                runtimeCaching:[{ urlPattern: /^https?.*/, handler: 'networkFirst' }
            ],
                importScripts:
                 ['/static/js/firebase-messaging-sw.js',
                 '/static/js/backgroundSync-sw.js'
                ]
            },

        }]

    ],
    {
        webpack: (config, { isServer }) => {
            if (ANALYZE) {
                const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer')

                config.plugins.push(new BundleAnalyzerPlugin({
                    analyzerMode: 'server',
                    analyzerPort: isServer ? 8888 : 8889,
                    openAnalyzer: true
                }))
            }

            config.module.rules.push(
                {
                    test: /\.md$/,
                    use: 'raw-loader'
                }
            )

            return config
        }
    },
    {
        exportPathMap: async () => {
            // we fetch our list of posts, this allow us to dynamically generate the exported pages
            const response = await fetch(`https://something.net/wp-json/wp/v2/posts`)
            const postList = await response.json()

            // tranform the list of posts into a map of pages with the pathname `/post/:id`
            const pages = postList.reduce(
                (pages, post) =>
                    Object.assign({}, pages, {
                        [`/blogDetail/${post.id}`]: {
                            page: '/blogDetail',
                            query: { id: post.id }
                        }
                    }),
                {}
            )

            // combine the map of post pages with the home
            return Object.assign({}, pages, {
                '/': { page: '/' },
                '/blog': { page: '/' },
                '/contact': { page: '/' },
                '/qui-sommes-nous': { page: '/qui-sommes-nous' },
                '/solutions': { page: '/solutions' },
            })
        }
    },
    {
        generateBuildId: async () => {
            // For example get the latest git commit hash here

            return 'v0.1.0'
        }
    }


);

**Comment by hanford** [comment]
is this still happening? We might be doing something messed up in windows environments with paths but I don't have access to a windows machine so I can't really debug.

Would love a PR with a fix if it is happening

**Comment by hanford** [comment]
Going to go ahead and close this. Probably related to using next-compose-plugins, and that issue is being tracked over here: https://github.com/hanford/next-offline/issues/69
