### ISSUE TITLE
SW registration failed next-offline

### ISSUE THREAD

**Issue by huynv0302** [hanford/next-offline#87]
help me! 
error: SW registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

**Comment by hanford** [comment]
can you please provide a link to your code? or a sample repo where this issue is happening?

I don't have enough information to take a look at this point

**Comment by MarkLyck** [comment]
I believe this is the same problem I'm having in issue #86
