### ISSUE TITLE
[Question] disable cache using next-offline

### ISSUE THREAD

**Issue by eldyvoon** [hanford/next-offline#89]
I've this in my next.config.js

https://github.com/zeit/next.js/blob/canary/examples/with-firebase-cloud-messaging/next.config.js

the point is just to create service-worker.js in .next, but by doing this I enabled caching which I don't really need, how can I disable that?

**Comment by eldyvoon** [comment]
any clue why this config failed when I run `npm run build`?

const withOffline = require("next-offline");

const nextConfig = {
  workboxOpts: {
    generateSw: false,
    swSrc: "./next/service-worker.js"
  }
};

module.exports = withOffline(nextConfig);

**Comment by hanford** [comment]
@eldyvoon ahh, i think it should be:

```js
const withOffline = require("next-offline");

const nextConfig = {
  generateSw: false,
  swSrc: "./next/service-worker.js"
};

module.exports = withOffline(nextConfig);
```

Those options are for `next-offline` everything in `workboxOpts` will get passed to workbox

**Comment by hanford** [comment]
To disable caching you'd specify a specific runtime caching rule under workboxOpts.

```js
module.exports = withOffline({
  workboxOpts: {
    runtimeCaching: [
      {
        urlPattern: /api/,
        handler: 'networkOnly',
      }
    ]
  }
})
```

where any request that matches urlPattern `/api/` will never be cached. urlPattern takes a regex so you should get fine grain control over any request.

You can read about some different handlers here: https://developers.google.com/web/tools/workbox/reference-docs/v2.1.2/module-workbox-runtime-caching

I think I've answered your question so going to close this issue.

Feel free to open another if you run into anything else.

**Comment by eldyvoon** [comment]
> To disable caching you'd specify a specific runtime caching rule under workboxOpts.
> 
> ```js
> module.exports = withOffline({
>   workboxOpts: {
>     runtimeCaching: [
>       {
>         urlPattern: /api/,
>         handler: 'networkOnly',
>       }
>     ]
>   }
> })
> ```
> 
> where any request that matches urlPattern `/api/` will never be cached. urlPattern takes a regex so you should get fine grain control over any request.
> 
> You can read about some different handlers here: https://developers.google.com/web/tools/workbox/reference-docs/v2.1.2/module-workbox-runtime-caching
> 
> I think I've answered your question so going to close this issue.
> 
> Feel free to open another if you run into anything else.

there's no way to disable the cache entirely using a flag? I want to use next-offline for the sake of putting my sw into `.next` folder.

**Comment by hanford** [comment]
I'd suggest doing this: https://github.com/webpack-contrib/copy-webpack-plugin

It doesn't make sense for next-offline to _not_ cache files, that's the point of the plugin!

**Comment by nishanBende** [comment]
@hanford I think this issue should be opened. 
What if I want to disable caching for all files but enable for a few ones (Like images, JS, CSS, my API server etc). 
In my use case, I have a web audio player, but I don't want to cache audio files and these files come from different domains, also the extensions can vary. Sometimes they don't have extensions but do have a ContentType 😐 

So I can't keep a regex of simple extensions or domains.
