### ISSUE TITLE
Render a custom "offline page" when page is not yet in SW cache

### ISSUE THREAD

**Issue by petertenhoor** [hanford/next-offline#93]
Hi there,

First of all; thanks for making this great next.js extension. It works like a charm. My service worker is registering, caching assets + pages and makes my project work offline.

This is great, unless a visitor has not yet visited the page before when he/she had an active internet connection. Then the default browser offline page is shown. That's why I was wondering; how would your workboxOpts object look when you want to display a next page (for example /offline) when the page that the visitor is trying to reach is not yet in the service worker cache?

Since the extension is called next-offline I personally think a custom offline page for pages that are not yet cached would be a nice feature to support out of the box.

I'm looking forward to hear your opinion on this matter.

Best regards,

Peter

**Comment by hanford** [comment]
@petertenhoor `next-offline` currently is just for the caching and offline mode of an application, I haven't added anything that you're requesting though it should be pretty easy to add on your own!

I'd suggest looking into this API that can let your application code know the state of your users connection.

[online status api](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events)
[online status react hook](https://github.com/rehooks/online-status)

If you do this high up in your component tree, you can basically say `isOnline ? <App /> : <OfflinePage />`

Hope that's helpful! I'm going to close this issue as it's not related to next-offline functionality, but feel free to comment and I'd be happy to help you figure out something that works for your app
