### ISSUE TITLE
Automatically serve workbox files for importWorkboxFrom: "local"

### ISSUE THREAD

**Issue by PatrickSachs** [hanford/next-offline#97]
The application I am currently writing must be able to run on a fully isolated intranet without physical access to the internet or data flowing through CDNs. 

For this reason I am using the workbox option `importWorkboxFrom: "local"`. This generates a `workbox-v3.6.3` folder in my `.next` folder with all required workbox JS files it in.

However when then opening the webapp a request to `https://example.local/workbox-v3.6.3/workbox-ws.js`  fails with a 404 error for obvious reasons. 

This could easily be worked around by adding the following line of code to my servers code:

```s
server.use("/workbox-v3.6.3", express.static(path.join(__dirname, "../.next/workbox-v3.6.3")));
```

However, I see one big issue with this: Should the workbox dependency of the library ever update(e.g. for 3.7.0) this will break without me immediately noticing.

For this reason I'd prefer if this library would automatically inject the necessary network handlers into the express application.

Or is there an already existing easier/more idiomatic way to achieve this?

**Comment by derekdowling** [comment]
You can have Workbox put the non-sw files it generates in a specific folder via `importsDirectory`. I would recommend putting it into your static folder:
```
{
  workboxOpts: {
    importsDirectory: 'static',
    importWorkboxFrom: 'local',
  },
}
```
Which I believe should solve this problem?

**Comment by hanford** [comment]
Going to close this, I think @derekdowling's answer is adequate
